### ISSUE TITLE
unpack .mo and .qm

### ISSUE THREAD

**Issue by hesss5** [Bioruebe/UniExtract2#107]
hi
please add support for unpacking or decompile  .mo and .qm
to .po and .ts file
this file type used for language file

**Comment by Bioruebe** [comment]
There are extractors for both file types, so it should be easy to add support.

> will be in or not?

Yes.

**Comment by hesss5** [comment]
where i can download it?

**Comment by HapaxOromenon** [comment]
> 
> 
> where i can download it?

See the section labelled "building from source" on https://github.com/Bioruebe/UniExtract2

**Comment by hesss5** [comment]
@Bioruebe
in this type of file sometimes i get this error
![shot](https://user-images.githubusercontent.com/23487445/65469212-72caa800-de73-11e9-8fe1-6776d8574636.png)
