### ISSUE TITLE
Extractor Updates

### ISSUE THREAD

**Issue by Skibicki** [Bioruebe/UniExtract2#110]
These are updates of software included with UniExtract2.
	7-Zip 19.00
	BCM 1.30
	De-Mole-Ition 0.6.0
	Enigma Virtual Box unpacker 0.55
        Exeinfo PE 0.0.5.3
        extractMHT 1.1    https://github.com/bambucode/extractMHT
	FLV Extract CL 1.6.5
	FSB files extractor 0.3.8
	GCFScape 1.8.6.0
	HelpDeco 2.1.4    https://sourceforge.net/projects/helpdeco/
        innounp 0.48
	JSWare MsiX 1.19.0.1
	LessMsi 1.6.3.0
	lzop 1.04
	MediaInfo 18.12
	MhtUnPack plugin 2.2
	Mtee 2.21    https://github.com/ritchielawrence/mtee
	Neko 2.2.0
	Pea 0.65.0.0
	QuickBMS 0.9.2.0
	SQLite 3.27.2.0
	Telltale TTARCH files extractor/rebuilder 0.3.1a
	UnRar 5.70 - Included in WinRAR installer
	unrpa 1.6
	Unshield 1.4.3
	UPX 3.95.0.0
	VIS3Ext 2.2.6777.0
	Wix Toolset Decompiler (Dark) 3.11.2318.0
	ZPAQ 7.15

**Comment by Bioruebe** [comment]
Merged into #152
