### ISSUE TITLE
Option/request?: use custom ffmpeg path / existing ffmpeg installation

### ISSUE THREAD

**Issue by Vagmer** [Bioruebe/UniExtract2#112]
Just installed this (thanks for your work keeping this project updated). Apparently the program makes an offer to download and install ffmpeg on the first launch (and when you try to extract video files), which I declined as I already have the ffmpeg binary on my system (which is not particularly small either). I couldn't find a method to point UniExtract2 to my existing ffmpeg.exe file. The folder of my ffmpeg.exe is even in my system PATH environmental variable, but to no avail here. 

I solved the issue for myself by creating a symlink (use `mklink` command in an elevated command prompt) as "[uniextract2 folder]\bin\x64\ffmpeg.exe" that points to my preexisting ffmpeg.exe file, however (unless I missed a built-in option for this), this could be an oversight you'd want to address inside the program.

**Comment by Juesto** [comment]
Same, how to install ffmpeg post-first-run?

**Comment by Vagmer** [comment]
Well, what you're asking doesn't really imply "Same". The answer: I believe that you can just try to extract a video file and then UniExtract will give an error/warning message that also gives you the option of automatically downloading & installing ffmpeg. Maybe there's an option to hide that message that you should disable if you have chosen it before, I don't remember.
Otherwise, I kind of already answered on how to do it manually: download the ffmpeg binary yourself and put ffmpeg.exe at the path "[uniextract2 folder]\bin\x64\ffmpeg.exe". Or place your ffmpeg.exe somewhere else and create a symlink to it in the same path, as mentioned.

**Comment by Juesto** [comment]
ah sorry and thanks
