### ISSUE TITLE
RPGMaker Decrypter dead download. which version goes?

### ISSUE THREAD

**Issue by Juesto** [Bioruebe/UniExtract2#113]
Clicking download says "File not found". I am not able to figure out what version of this is supposed to go to become "Installed".

**Comment by BravoOneCharlie** [comment]
This is the version that it's trying to download. https://www.4shared.com/rar/oN2hGDGbda/RPGDecrypter.html

**Comment by Juesto** [comment]
okay... can you please put it on another sharing site? 4shared has ads and is login protected

**Comment by TheGuyInShades** [comment]
What site do you want me to upload it to?

**Comment by TheGuyInShades** [comment]
I uploaded it to dropbox. https://www.dropbox.com/s/fanwocp28yri0sb/RPGDecrypter.rar?dl=0

**Comment by Juesto** [comment]
thanks

**Comment by Cool-Pan** [comment]
I found a Java version and didn't know if it was what you needed.

[Java-RPG-Maker-MV-Decrypter](https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter)

**Comment by Juesto** [comment]
It's preferable for Biorube to update this.
Java ver isn't the one.
