### ISSUE TITLE
64 vs 32 bit binaries in bin directory

### ISSUE THREAD

**Issue by stup4crsa** [Bioruebe/UniExtract2#115]
This is in 'UniExtractRC1':

Almost all (59) of the .exe files in the bin directory are 32 bit:  (PE32 executable (GUI) Intel 80386, for MS Windows), and presumably run on both 32 / 64 bit platforms.

However there are 3 that are 64 bit only (PE32+ executable (console) x86-64, for MS Windows):

    ttarchext.exe
    unrpa.exe
    unshield.exe

What that the intention?

John Refling

P.S. Thx for maintaining this software.

**Comment by Bioruebe** [comment]
ttarchext and unrpa have been replaced in RC 2. unshield still needs to be recompiled.

**Comment by Bioruebe** [comment]
Merged into #152
