### ISSUE TITLE
7z warnings result in failed extractions.

### ISSUE THREAD

**Issue by jeff-bb** [Bioruebe/UniExtract2#116]
For example, a signed CAB file extracts fine, but has a warning that there is data after the end of the archive. Uniextract treats this as a failure and stops processing and removes the extracted files. I'd prefer it left the files behind and wasn't considered a full failure.

2018-10-15 11:44:14:101	Executing: C:\WINDOWS\system32\cmd.exe /d /c ""C:\Users\userid\Utils\UniExtract\bin\x64\7z.exe" l "C:\Users\userid\Downloads\20568088_641d9df86729c3bde761016fc2e45c9798231e2b.cab"
2018-10-15 11:44:14:210	
7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 117053 bytes (115 KiB)

Listing archive: C:\Users\userid\Downloads\20568088_641d9df86729c3bde761016fc2e45c9798231e2b.cab

--
Path = C:\Users\userid\Downloads\20568088_641d9df86729c3bde761016fc2e45c9798231e2b.cab
Type = Cab
WARNINGS:
There are data after the end of archive
Physical Size = 100917
Tail Size = 16136
Method = LZX:21
Blocks = 1
Volumes = 1
Volume Index = 0
ID = 0

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2013-06-03 00:52:06 ....A         2857               SVK9PL.inf
2013-06-03 00:52:06 ....A       135168               SVK9PL.sys
2013-06-03 00:52:06 ....A       161280               SVK9PL64.sys
2013-06-03 01:06:42 ....A         8584               svk9plf.cat
------------------- ----- ------------ ------------  ------------------------
2013-06-03 01:06:42             307889       117053  4 files

Warnings: 1

2018-10-15 11:44:14:570	Extraction finished, success: 0
2018-10-15 11:44:14:570	Terminating - Status: failed

**Comment by pjaudeie** [comment]
The same problem affects exe files that contain just the 'data' but 7-Zip (19.0.0.0) sees as a valid archive. This is illustrated with two publicly available installer files from Citrix: CitrixWorkspaceApp.exe and ReceiverCleanupUtility.exe.
These are available via webpages:
https://www.citrix.com/downloads/workspace-app/windows/workspace-app-for-windows-latest.html
https://support.citrix.com/article/CTX137494
The latter has ReceiverCleanupUtility.exe zipped, so naturally unzip then test with UniExtract.
7-Zip has no issue in performing an extraction of either exe file whereas UniExtract fails with scan (an so extraction also).

**Comment by ltGuillaume** [comment]
I would suspect that the errorlevel 7z gives would differ between warnings and errors, so UniExtract should act accordingly.
