### ISSUE TITLE
failed extracting sitx

### ISSUE THREAD

**Issue by NetworkPro** [Bioruebe/UniExtract2#117]
failed extracting the following sitx
https://dox.abv.bg/download?id=63a63fa8e8#
https://www.solidfiles.com/v/jXqZMD3d3zpDy

**Comment by TheGuyInShades** [comment]
I'm not sure that UniExtract can decompress StuffIt X Archives, I think the StuffIt expander it uses can only extract regular (.sit) Stuffit Archives. I do happen to have StuffIt for Windows, I extracted the files and put them into a Zip file for you. https://www.dropbox.com/s/lnbuikleqybx7wy/64_Books_for_Macintosh_Developers.zip?dl=0

**Comment by TheGuyInShades** [comment]
I'll probably want to delete it off dropbox at some point so let me know when you download it.

**Comment by NetworkPro** [comment]
Done thanks.
