### ISSUE TITLE
Feature Request: Disable Periodic Automatic Update

### ISSUE THREAD

**Issue by ghost** [Bioruebe/UniExtract2#118]
Can we please have an option (maybe under Preferences) to disable periodic automatic updates? I personally will update triddefs myself now and then, and then once in awhile Uniextract updater will replace the up- to-date defs with the older defs that are currently in this repository. Thank you for your consideration.

**Comment by Bioruebe** [comment]
Added in eb453333d78f5e27668279d9e56f8b51de706acf

Until I release the update you can - as a workaround -  just set update interval to a very high value.

I'm also considering adding checks to prevent overwriting local files that are newer than the ones on the server. Maybe as an option for all the people, who like to update their files manually ;)
But that's still a todo and not the highest priority at the moment.
