### ISSUE TITLE
RC2

### ISSUE THREAD

**Issue by D1mar0n** [Bioruebe/UniExtract2#127]
Hello! I have version RC1, and how to upgrade it to version RC2?

**Comment by Bioruebe** [comment]
RC 2 is not finished yet. It might take a little bit more time until I release it.

**Comment by D1mar0n** [comment]
Thanks for the answer! I look forward to the release of the new version. Good luck!
На 02.03.2019 10:31:24, William Engelmann <notifications@github.com> писал:
RC 2 is not finished yet. It might take a little bit more time until I release it.

**Comment by Bioruebe** [comment]
Released :)

**Comment by D1mar0n** [comment]
Thanks!!!
На 13.03.2019 7:47:10, William Engelmann <notifications@github.com> писал:
Released :)
