### ISSUE TITLE
Minor UI item: "scan" appears as "scar"

### ISSUE THREAD

**Issue by vatterspun** [Bioruebe/UniExtract2#13]
Setup: Win7x86 using v2 beta 2b

Highllighted in red box:
http://i.imgur.com/NSkBYq9.png

**Comment by acook** [comment]
Looks like the "n" is cut off by a too-small bounding box. 

Changing [this line](https://github.com/Bioruebe/UniExtract2/blob/a4459f6fc40a8ea2021dee0cf88ae15362393606/UniExtract.au3#L4446) to something like this might solve the problem:
~~~autoit
Global $GUI_Main_Scan = GUICtrlCreateRadio(t('TERM_SCAN'), GetPos($guimain, $GUI_Main_Extract, 10), 3, Default + 2, 15)
~~~
