### ISSUE TITLE
Suggest: Add an selection window when it fails to extract anything

### ISSUE THREAD

**Issue by qazmko1029** [Bioruebe/UniExtract2#130]
This is a suggestion rather than issue, to add a window when program fails to detect actual type of compression method. It is actually partially featured in original UniExtractor, but here it doesn't exist.
Besides, there should also be an option to manually select decompression method in context menu and main window as I suggest. Hope to be implemented.

**Comment by Bioruebe** [comment]
Merged with similar requests into #196.
