### ISSUE TITLE
Feature request: ability to easily copy-paste scan output

### ISSUE THREAD

**Issue by vatterspun** [Bioruebe/UniExtract2#14]
NOTE: This is very low priority as I'm anticipating the needs of others and don't know if this is an actual concern.

**Current behavior**

When running the program on a setup file with "Scan" selected, you can press Ctrl+C on the resulting window and then paste the text into another window but the text doesn't look anything like the formatting in the output window.

**Requested behavior**

Somehow simplify the process of saving that data, perhaps a "save as" button to dump to text file?

**Comment by gvp9000** [comment]
paste it in notepad++ not in notepad ...

**Comment by gvp9000** [comment]
Recompile the current au3 ... i think it's ok now ... #14
