### ISSUE TITLE
Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by lejuculu** [Bioruebe/UniExtract2#140]
UniExtract.exe is detected as Trojan:Win32/Azden.A!cl by Microsoft Security Essentials

**Comment by vatterspun** [comment]
Which version? 2.0.0 RC 2

Looks like a false positive with only 4 out of 54 tools listing it as problematic: https://www.virustotal.com/en/file/c0b36042e8cd4f2169c7da1998e46c020c6578077b468d253312f010ffda3868/analysis/

SHA 256: C0B36042E8CD4F2169C7DA1998E46C020C6578077B468D253312F010FFDA3868

**Comment by Bioruebe** [comment]
I submitted a incorrect detection report. Now it's up to Microsoft to update their malware definitions.

**Comment by PMoro** [comment]
Right now it is passing Windows Defender checks!
