### ISSUE TITLE
7-Zip should be tested by default on unknown formats

### ISSUE THREAD

**Issue by ltGuillaume** [Bioruebe/UniExtract2#144]
I have recently switched to UniExtract v2 from 1.9.22.209 and have found many occasions where v2 does not successfully extract installers, while v1.9 works just fine.

In most of these cases, 7-Zip was simply used to extract from the installer by v1.9, whereas v2 states "it appears to be a Telltale Game archive" (which is bullshit). As such, I propose that v2 also tries to extract using 7-Zip if the file format is not detected.

An example is the Vivaldi installer (www.vivaldi.com).

**Comment by Bioruebe** [comment]
For most files, 7z is already the last extractor to try if everything else failed. I was really surprised that it did not happen for many executables...

So thanks for pointing it out to me. I found the source of the problem and changed the code accordingly.

**Comment by ltGuillaume** [comment]
Cool, thank you!

**Comment by ltGuillaume** [comment]
I have updated to 2.0.0 RC3, which supposedly should have fixed this:
> Fixed some executables not being tested with 7zip

However, Vivaldi installers are still recognized as TellTale game archives, instead of being extracted with 7-Zip.

(Furthermore, I keep getting a message that there's a new version, even though I updated moments ago).

**Comment by Bioruebe** [comment]
> (Furthermore, I keep getting a message that there's a new version, even though I updated moments ago).

My apologies, there was a problem with the updater. It downloaded the wrong UniExtract.exe (RC 2 instead of RC 3). Thanks for reporting back and helping me find the bug.

I released a hotfix, please search for updates *twice*. The first update is the patch to fix the updater, the second should download RC 3.

**Comment by ltGuillaume** [comment]
Tested and working now, thank you! 👍

**Comment by ltGuillaume** [comment]
Please have a look at https://www.fosshub.com/IrfanView.html installers. This should also be extracted using 7-zip, but instead it gives an error message.
