### ISSUE TITLE
It would be nice if the show open folder would open in Total Commander like with other apps.

### ISSUE THREAD

**Issue by mzso** [Bioruebe/UniExtract2#147]
Hi!

I have set up my system to open folders in Total Commander via this:
https://www.ghisler.ch/wiki/index.php?title=Explorer_integration

But apparently this doesn't work for Uniextract2 for some reason.

**Comment by Bioruebe** [comment]
Thanks for the report, that's something I would have never thought about.

I guess you mean the option 'Open folder after extraction'?

I made a change in a recent commit, which should fix the issue. You can try the [nightly version](https://github.com/Bioruebe/UniExtract2#nightly-builds) if you want to test it yourself.

**Comment by mzso** [comment]
> 
> 
> Thanks for the report, that's something I would have never thought about.
> 
> I guess you mean the option 'Open folder after extraction'?
Yes.

> 
> I made a change in a recent commit, which should fix the issue. You can try the [nightly version](https://github.com/Bioruebe/UniExtract2#nightly-builds) if you want to test it yourself.

Cool. Will do.

**Comment by mzso** [comment]
And it works well, thanks!
