### ISSUE TITLE
[Minor] Plugins menu error message

### ISSUE THREAD

**Issue by vatterspun** [Bioruebe/UniExtract2#15]
I got some odd results from going through the program in (what I expect) is a fairly common operation.  

Setup: Win7x86
Steps: From the menu, Help -> Plugins.  Click Finish.

Defect: 

```
> AutoIt Error
> ---------------------------
> Line 26319  (File "C:\Users\USERNAME\Desktop\Desktop2\programs\UniExtract2\UniExtract.exe"):
> Error: Variable subscript badly formatted.
> ---------------------------
> OK   
```

**Workaround**: click the X in the corner rather than "Finish"

**Comment by Bioruebe** [comment]
Fixed in master.
