### ISSUE TITLE
Some out-of-date extractor files

### ISSUE THREAD

**Issue by pol098** [Bioruebe/UniExtract2#150]
As of UniExtrac2 v2.0.0 RC1 some extractor files are still out of date:
pea.exe: v0.53 included, v0.65 is available (already reported 11Se18)
iso.wcx: version included 19456b 19/07/11; there is a later version, I think beta: 52224b 17/08/13
triddefs.trd is frequently updated, so nearly always out of date
unarc.exe (from FreeArc). included is v0.66 214,016b, 19/05/10. There is v0.67, 333,312b, 15/03/14
unrar.exe: there is a new v5.71 of 27/04/19
[NewerExtractorsForUE2RC2.zip](https://github.com/Bioruebe/UniExtract2/files/3127921/NewerExtractorsForUE2RC2.zip) (refers to v2.0.0 RC1, not RC2)

**Comment by Bioruebe** [comment]
Merged into #152
