### ISSUE TITLE
Microsoft Windows Defender false detect Trojan in UniExtract.exe

### ISSUE THREAD

**Issue by ghost** [Bioruebe/UniExtract2#154]
Microsoft Windows Defender (def. virus 1.295.638.0) running in Windows 10 Pro, false detect Trojan:Win32/Woreflint.A!.cl in UniExtract.exe (version 2.0.0 RC 2b (12.04.2019)).
____________________________________________________________________________________________________
Printscreens from Windows Defender (language: Brazilian portuguese):
____________________________________________________________________________________________________

![WinDef1](https://user-images.githubusercontent.com/43634578/59432152-04c70d00-8dbd-11e9-879b-6c0136634d83.gif)
____________________________________________________________________________________________________
![WinDef2](https://user-images.githubusercontent.com/43634578/59432153-055fa380-8dbd-11e9-9a3b-1fd18b5f91fc.gif)

**Comment by TAbdiukov** [comment]
Thanks! But probably should go to #78

**Comment by Bioruebe** [comment]
Thanks for the info. I sent a false positive report and according to VirusTotal it's not detected any more.
