### ISSUE TITLE
Download/update  nightly build

### ISSUE THREAD

**Issue by harryray33** [Bioruebe/UniExtract2#156]
I have this set to install beta updates but I keep getting an error message stating that some file can't be updated...Is there any way to download the latest nightly build directly without going through the update process?

Thanks

**Comment by Bioruebe** [comment]
Here you go: [nightly build](https://update.bioruebe.com/uniextract/files/nightly.zip)

If you only need a specific file, you can download it directly from 
`https://update.bioruebe.com/uniextract/nightly/<path-to-file>`,
e.g. `https://update.bioruebe.com/uniextract/nightly/changelog_minor.txt`

Thanks for your report, I added improving the update failed error message to my todo list, so we can troubleshoot similar problems in the future.
