### ISSUE TITLE
[suggestion] properly handling MSU-Files - Windows Update standalone patch

### ISSUE THREAD

**Issue by eladkarako** [Bioruebe/UniExtract2#159]
M$ describes the file <a href="https://support.microsoft.com/en-us/help/934307/description-of-the-windows-update-standalone-installer-in-windows">like so</a>.

Opening it with 7zip isn't very helpful: <br/>
<img src="https://i.imgur.com/n6uEbh1l.png" />

UniExtract1.6 and UE2 address it as a 7zip archive filled with CAB files ("<code>MSZip</code>"), 
which is something like an MSI, but the files-description tree is not as clear as in the MSI format, 
essentially keep opening the (7zip) it will give you bunch of nameless files (1,2,3,...) and few core -like ones.

<hr/>

This tool: https://gist.github.com/anonymous/d55f494982c0097111d3263cf7099c9d#file-patchextract125-ps1
can extract it, it's a powershell batch-file, which uses expand.exe and builds the folder-file tree,
it can handle files that are strictly x86/x64 or with both combined.

I've wrapped it with a batch-file to enable me some drag&amp;drop functionality in here:
https://github.com/eladkarako/mods/blob/store/MSU-Extractor
so it will dump the files into a folder named like the filename with <code>_</code> prefix/suffix wrapping.

**Comment by TAbdiukov** [comment]
Suggest flaring with `new-extractor`
