### ISSUE TITLE
Archive in unicode folder gets deleted when space in Temp folder is too low

### ISSUE THREAD

**Issue by danielmmmm** [Bioruebe/UniExtract2#16]
When an archive (e.g. ZIP) resides within a folder that has unicode characters in its name, extraction of the archive may fail and the archive might get deleted.

The following conditions have to be met:
1) The folder containing the archive must contain unicode characters (e.g. ø)
2) The free space in the Temp folder must be big enough for the archive itself
3) The free space in the Temp folder must be smaller than the archive and its content combined

Example:
D:\unicøde\archive.zip          (3 GB)
C:\Temp          (free space on C: 4 GB)

Under these conditions, UniExtract will copy the archive to the Temp folder, delete the original archive and attempt to extract the temporary archive inside the Temp folder. The extraction fails due to low space, and UniExtract quits with the following error:

AutoIt Error - Line 24439 (File "D:\UniExtract\UniExtract.exe"): Error: Incorrect number of parameters in function call.

The temporary archive will, of course, not be deleted from the Temp folder after UniExtract crashes.

PS: May I ask why the original archive is deleted after it was copied to the Temp folder? This seems to be highly dangerous in case of an error.
PPS: Thanks a lot for this tremendously useful tool! :-)

**Comment by Bioruebe** [comment]
Thanks for the detailed report, I can confirm the problem.

> May I ask why the original archive is deleted after it was copied to the Temp folder? This seems to be highly dangerous in case of an error.

It is. The original file is moved to the temp dir to make the process a lot faster than 'copy and delete'. (Of course this only works if the file is on the same drive as the temp dir. And it has its problems.)

**Comment by danielmmmm** [comment]
> ... I can confirm the problem.
Great! I was afraid it might have been confusing :-)

I get the point of moving the file. Would it be hard to check, if the Temp directory is on another partition? Or to move the file back in case of an error?

Anyways, thanks a lot for developing uniextract further. This tool is incredibly powerful and I couldn't live without it.
