### ISSUE TITLE
jsMSI extractor not working

### ISSUE THREAD

**Issue by HapaxOromenon** [Bioruebe/UniExtract2#160]
If you try to extract an MSI file using the default option of jsMSI, it just opens the jsMSI graphical interface, from where you have to manually select the file location and directory to extract it to (see attached screenshot).
![UniExtract jsMSI](https://user-images.githubusercontent.com/40141645/62091263-fdbe6600-b267-11e9-894a-02e0cfc20d96.png)
The expected behaviour is that UniExtract should pass these parameters to jsMSI so that the extraction occurs without requiring any user input.

**Comment by mzso** [comment]
I just had the same experience, but also:
- The source folder is spammed with useless .CAB files. 
- When I close MSI Unpacker on finish I get a further folder created (to the path specified in uniextractor at startup) with those same .CAB files copied. So more spamming.
- It's be nice if I wouldn't get an extraction failed message when I abort and close the MSI Unpacker window.

So essentially it works. It's just very cumbersome and unpractical. It's easier to use "MSI Administrative Installer"(back translated to english).

**Comment by Bioruebe** [comment]
That's an interesting find, thank you. Looks like the current version of jsMsi dropped command line support. I rolled back to the previous build; this should make things work again.
