### ISSUE TITLE
Support for GoPro MILBEAUT binary ROM update images?

### ISSUE THREAD

**Issue by altimumdelta** [Bioruebe/UniExtract2#162]
Not that I would really need it, but GoPro seemed to botch the HERO7 Black having freezing issues, with an update released recently on 14 August 2019 that some say didn't work.

But it may be cool playing with the FW (maybe has some hidden features) even if fixing anything's out of question.

UniExtract2 Thinks it's a game archive initially, I selected not-on-the-list and it didn't work as I expected:

`4D 49 4C 42 45 41 55 54 03 00 00 00 00 10 01 00 30 48 00 47 00 00 00 40 45 26 FE 3F B1 26 FE 3F B1 26 FE 3F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 BD 6A FE 3F 00 00 00 00 00 00 00 00 71 6B FE 3F B5 6B FE 3F 69 24 FE 3F 73 24 FE 3F 7D 24 FE 3F 87 24 FE 3F 91 24 FE 3F A3 24 FE 3F 9B 24 FE 3F AB 24 FE 3F B3 24 FE 3F B5 24 FE 3F BD 24 FE 3F C5 24 FE 3F CD 24 FE 3F D5 24 FE 3F 00 00 00 00 B1 26 FE 3F B1 26 FE 3F B1 26 FE 3F B1 26 FE 3F B1 26 FE 3F B1 26 FE 3F B1 26 FE 3F DD 24 FE 3F 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 E5 24 FE 3F EF 24 FE 3F F9 24 FE 3F 03 25 FE 3F 0D 25 FE 3F 45 26 FE 3F 10 B5 06 4C 23 78 00 2B 07 D1 05 4B 00 2B 02 D0 04 48 00 E0 00 BF 01 23 23 70 10 BD A0 20 FF 3F 00 00 00 00 24 0C FF 3F 08 B5 08 4B 00 2B 03 D0 07 48 08 49 00 E0 00 BF 07 48 03 68 00 2B 00 D1 08 BD 06 4B 00 2B FB D0 98 47 F9 E7 00 00 00 00 24 0C FF 3F A4 20 FF 3F 9C 20 FF 3F 00 00 00 00 37 B5 19 4C A3 68 00 2B 02 D0 A3 68 02 68 1A 60 22 68 03 68 61 68 20 33 8A 18 93 42 21 D3 13 4B 05 1C 1B 68 00 2B 11 D0 00 23 01 93 10 4B 11 48 19 68 40 22 01 AB 07 F0 FD FD 01 28 06 D1 01 9B 00 2B 03 D0 80 22 0C 4B 52 05 1A 60 E3 68 00 2B 04 D0 01 2B 06 D1 23 68 2B 60 03 E0 09 F0 18 FA 00 E0 03 60 37 BD C0 46 C0 20 FF 3F BC 20 FF 3F 30 7A FF 3F DB 81 FE 3F 04 ED 00 E0 1F B5 09 F0 85 F8 00 23 FF 22 01 A8`

IDK What other cameras use, I don't have any other GoPro, nor this one it's actually borrowed so I won't have it forever, but you can get manual update file from the official site using manual update guide, you don't need to enter a real serial number, fake one will work with a throwaway email, it's not required but forced, no way to skip registration.

**Comment by altimumdelta** [comment]
Well the first start of the SN is required to be correct, but the site host is raw and not checking so I think this link will work for everyone:

https://device-firmware.gp-static.com/30/HD7.01/camera_fw/01.80.00/UPDATE.zip

**Comment by Bioruebe** [comment]
Sorry to disappoint, but firmware is out-of-scope, because it would be almost impossible to extract anything useful. The FW and the installer are built for a specific piece of hardware, so it would be very hard to create an extractor. I'm sure there are people capable of fixing updates and finding hidden features, but that's not where my skills lay.
