### ISSUE TITLE
Improvements to ffmpeg installation

### ISSUE THREAD

**Issue by mirh** [Bioruebe/UniExtract2#17]
- The program should check whether it has permissions to write in its own folder (in my case, it hadn't)
- Possibly ask to be launched as administrator if it hasn't
- After a successful download, it should automatically proceed to next step. 
- "_Next_" button would be clearer if stating "_Skip_"

**Comment by Bioruebe** [comment]
Permission check already implemented in master.
'automatically proceed to next step' is in the code and should have worked, needs to be checked again.

**Comment by Bioruebe** [comment]
With the latest changes to the first-start assistant (15bdac11e9f39be38df0205b47eab43ad6d19953) everything has been fixed.
