### ISSUE TITLE
Many included binaries are not licensed for commecial use

### ISSUE THREAD

**Issue by peflo** [Bioruebe/UniExtract2#170]
A number of the helper binaries (among those listed as freeware) are flagged on their homepages as not licensed for commercial use.  Since UniExtract2 itself is GPLv2 this could easily lead someone to inadvertently download and use these tools for commercial purposes.  

A disclaimer in the license section of the readme clarifying this would alleviate this concern.

**Comment by vatterspun** [comment]
I think this was also an issue with the original Legroom project: https://www.portablefreeware.com/forums/viewtopic.php?p=23073#p23073

**Comment by peflo** [comment]
Thanks @Bioruebe , much appreciated!
