### ISSUE TITLE
Error: Array variable has incorrect number...

### ISSUE THREAD

**Issue by Sopor** [Bioruebe/UniExtract2#174]
When running UniExtract2 for the first time it asked me to download ffmpeg but after the download i got this message:

![image](https://user-images.githubusercontent.com/5789283/70382776-70032d80-1961-11ea-966b-ecf4a0e12cc5.png)

It seems to have copy ffmpeg to the `bin\x64\` folder even if it is an older version, 4.1.3.

**Comment by htes9** [comment]
Can reproduce on 2.0.0 RC 2b 
![unknown](https://user-images.githubusercontent.com/7214961/76087364-4d130480-5fb6-11ea-8bed-40fa78fdaf9a.png)
