### ISSUE TITLE
Request: Replace InnoUnp with innoextract

### ISSUE THREAD

**Issue by hgdagon** [Bioruebe/UniExtract2#177]
innoextract is much more useful now than InnoUnp. It can correctly extract GOG Galaxy installers, GOG rar-based installers, as well as installers made with a custom/modified version of Inno Setup.

https://constexpr.org/innoextract/innoextract.1

**Comment by CeruleanSky** [comment]
I came here for the same issue.
I just used UniExtract2 on a GOG file and it named all the files File001.bin etc, but thanks to your suggestion, I tried innoextract and it recreated all the directories and renamed the files appropriately, the fact that it has additional support and commands for GOG files is a bonus.

**Comment by Lokotito** [comment]
I think it would be an important update
