### ISSUE TITLE
GOG installation executables don't fully extract files

### ISSUE THREAD

**Issue by arnoldsecret** [Bioruebe/UniExtract2#178]
![Untitled](https://user-images.githubusercontent.com/41223243/72759435-b1e5eb80-3c10-11ea-831c-fa2a51c91381.png)
The installation folder still says it's 550mb, but looking at the {tmp} folder, it's all encrypted files that only the GOG installer can recognize.

**Comment by Bioruebe** [comment]
Thanks for reporting the problem.

This will be fixed by switching to innoextract as discussed in #177.
