### ISSUE TITLE
Uniextract RC3 beta - Trojan:Win32/Wacatac.D!ml infected

### ISSUE THREAD

**Issue by JohnTemplar** [Bioruebe/UniExtract2#180]
UniExtract.exe is detected as malware 'Trojan:Win32/Wacatac.D!ml' when updating Uniextract to RC3

[https://imgur.com/awMwhvQ](url)

**Comment by vatterspun** [comment]
It's likely a false-positive, but there are ways you can be sure.  What service are you using to look for malware?  Did you try running the download past VirusTotal, which checks the program against multiple services?

**Comment by JohnTemplar** [comment]
Windows 10 Windows Defender kicks in when updating Uniextract to RC3 using the built-in update function. I know of VirusTotal and I know it most likely it's false positive, but it does not help me, I want to use the app. RC3 *.exe wasn't flagged until 2-3 months ago, last time I've checked.

**Comment by vatterspun** [comment]
> I know it most likely it's false positive, but it does not help me, I want to use the app

You can download an older version of the program that may not trigger the warnings, but this is an ongoing problem with Windows Defender and similar tools.  You're welcome to submit the program for exception: https://answers.microsoft.com/en-us/windows/forum/windows_10-security/how-can-i-report-a-false-positive-for-a-site/e6912006-675b-4484-90ed-5284b770b4fb

Or you can download an earlier release: https://github.com/Bioruebe/UniExtract2/releases

**Comment by zdm** [comment]
You should uninstall windows defender and all other "antiviruses".

**Comment by vatterspun** [comment]
> You should uninstall windows defender and all other "antiviruses".

Although I ran without any kind of antivirus for several years, there are too many cases of malware sneaking into trusted software to dump AV entirely.  Some AV programs are worse about false-positives than others.  I recommend BitDefender.

**Comment by htes9** [comment]
Reason is autoit, you should consider it as a false-positive.

![unknown](https://user-images.githubusercontent.com/7214961/76087636-dde9e000-5fb6-11ea-8041-f68793be76e5.png)
![unknown](https://user-images.githubusercontent.com/7214961/76087707-007bf900-5fb7-11ea-9051-d73245fae992.png)
