### ISSUE TITLE
Difference in FIRSTSTART_PAGE4 across localizations

### ISSUE THREAD

**Issue by htes9** [Bioruebe/UniExtract2#182]
Different localizations show the presence of FIRSTSTART_PAGE4 inside 2.0.0 RC3, as a consequence the page with the download of ffmpeg is showed but it misses the download button using First Start Assistant, if that is removed, I will consider removing FIRSTSTART_PAGE4 from all the localizations.

![unknown](https://user-images.githubusercontent.com/7214961/76089348-c4966300-5fb9-11ea-88b2-d081004dad15.png)

**Comment by Bioruebe** [comment]
Thanks for reporting the problem. I completely forgot to update the localizations after removing page 4. Fixed now :)
