### ISSUE TITLE
Cascaded context menu in XP SP3?

### ISSUE THREAD

**Issue by temp10min** [Bioruebe/UniExtract2#183]
The "cascaded" option in the context menu settings is grayed out on XP. Could you make it work, please?
If needed, installing a shell extension .DLL is fine.

**Comment by Bioruebe** [comment]
The simple way to create cascading context menus that UniExtract uses (`SubCommands` registry key) only works on Windows 7 and newer. I'm not familiar with shell extensions, and to be honest it's not worth the time and maintenance work for me.

Without the 'cascading' option the items only take a bit more space, but no functionality is lost, it's just a little inconvenience. Unfortunately, if you need to use an outdated operating system, you have to settle for it. Sorry.

**Comment by temp10min** [comment]
My issue is that by using both UniExtract and your UniExtract2 i get a mix of similar menu entries with no way to tell which of the two programs they start...
Would it be possible to at least add icons or a prefix?

**Comment by Bioruebe** [comment]
Icons are actually there, but same problem: only newer versions of Windows can display them :(

However, it is possible to rename the context menu items in any way you like. There's no simple way to do so, though, you have to manually edit a file:

Open UniExtract's program directory, find the language file you are using (`English.ini` or anything from the `/lang` subdirectory) and edit it with notepad or any other plain text editor.

At the bottom of the file you can find
```
; Context Menu integration
EXTRACT_FILES = "UniExtract &Open"
EXTRACT_HERE = "UniExtract &Here"
EXTRACT_SUB = "UniExtract to &Subdir"
EXTRACT_LAST = "UniExtract to &last dir."
SCAN_FILE = "Scan &File"
```

Simply change the part in `"` to whatever you want, e.g. 
`EXTRACT_FILES = "Bio-UniExtract &Open"`
save the file, start UniExtract, open the `Context Menu Entries` dialog and click `OK`.

**Comment by temp10min** [comment]
This does the job fine, thank you!
