### ISSUE TITLE
Use DiE (Detect It Easy) instead of PEiD

### ISSUE THREAD

**Issue by LordNoteworthy** [Bioruebe/UniExtract2#186]
Hello,

DiE (MIT licensed) is regularly updated: https://github.com/horsicq/Detect-It-Easy and have more accurate sig detection than PEiD.

Maybe that is something to consider.

Cheers.

**Comment by Bioruebe** [comment]
Thanks for the recommendation.

At the moment PEiD is only used for a handful of file types; main detection of executable files is done by Exeinfo PE, which works great so far. So I'm not sure if we need another detector at the moment, but I'll keep it in mind.
