### ISSUE TITLE
In RC3, the main window is skewed.

### ISSUE THREAD

**Issue by wvxwxvw** [Bioruebe/UniExtract2#187]
In RC3, the main window is skewed.
![2020 03 23_075735](https://user-images.githubusercontent.com/13194155/77282924-3a017380-6cdc-11ea-894e-c75dcae926b2.jpg)
Everything is skewed, the words do not fit, the fields creep over the text, the buttons lie on top of each other. Please make normal, at least as in RC2:
![2020 03 23_075811](https://user-images.githubusercontent.com/13194155/77283047-8947a400-6cdc-11ea-8440-f745d69a4a27.jpg)

**Comment by Bioruebe** [comment]
Thanks for reporting the problem.

In RC 3 I made the main window slightly bigger, but apparently the new minimum size was not applied correctly.

Please update UniExtract RC3, the new version should fix the window size.

**Comment by wvxwxvw** [comment]
It's all right now.

It would also be nice to stretch the window and fields in the settings window.
![2020 03 26_034749](https://user-images.githubusercontent.com/13194155/77599231-268d1d00-6f15-11ea-9c2c-4a0960d6e050.jpg)

**Comment by Bioruebe** [comment]
I increased the size of the checkbox labels.

The text 'Search for updates' is quite long in some languages, that's why the update interval select field is smaller than the language select.

![ue_settings_combo](https://user-images.githubusercontent.com/3521951/78703346-47d50c80-790a-11ea-954a-01fa6920123d.png)

**Comment by wvxwxvw** [comment]
@Bioruebe 
In Russian, too, long, so I made the second arrow. I believe that you need to increase the entire window and the left field in particular.
You can see that in addition to "search for updates" does not fit two more lines.

**Comment by Bioruebe** [comment]
Of course, that makes sense. I just misunderstood your arrow.

Is this ok?

![ue_settings_ru](https://user-images.githubusercontent.com/3521951/78704795-bca94600-790c-11ea-91be-2c0bd3d89930.png)

**Comment by wvxwxvw** [comment]
Everything is fine, just updated now. Thanks!
I couldn't shorten the top line, only if I cut the words.
