### ISSUE TITLE
2.0.0 RC 2 can't extract InstallShield .Z archives

### ISSUE THREAD

**Issue by headsetguy37** [Bioruebe/UniExtract2#189]
It detects them as InstallShield files, but for whatever reason, it can't extract them. The error, ironically, is "Unknown extension". I am able to extract them using 1.6.1. I think this may be because i3comp.exe is included with 1.6.1, but isn't even an optional plugin for 2.0.0.
I have attached the most recent log file here, and have also sent several using the feedback option.
[2020-03-31_11-28-12_UNKNOWNEXT_main.z.log](https://github.com/Bioruebe/UniExtract2/files/4410771/2020-03-31_11-28-12_UNKNOWNEXT_main.z.log)

**Comment by Bioruebe** [comment]
Thanks for your report. I already fixed the problem in RC 3, so extraction should work again in the next version of UniExtract.
