### ISSUE TITLE
Updater is broken

### ISSUE THREAD

**Issue by HapaxOromenon** [Bioruebe/UniExtract2#191]
Clicking 'Help -> Check for Updates' brings up a message saying that an update is available. I click 'yes' and it updates UniExtract.exe and docs/bcm_readme.txt. UniExtract re-opens. But then clicking 'Help -> Check for Updates' again gives the same message as before, still saying that an update is available. One can keep updating and it still always says an update is available, when it should say that you are now on the latest version.

**Comment by Chaprnks** [comment]
Having the same issue here. Current version on the uniextractor shows "RC3". When I click update, it says "new update found, RC3". For testing purposes, I click update, it goes to the nightly url & installs. Once it re-runs, it shows the same RC3, and the "update available" cycles again, indefinitely.

**Comment by Bioruebe** [comment]
There was a server-side problem, nightly updates should work again.

**Comment by Chaprnks** [comment]
Awesome, thank you!
