### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by RoyiAvital** [Bioruebe/UniExtract2#20]
Hello,

Could you offer a portable version?

Namely all configuration is saved locally and no registry keys are created.

Thank You.

**Comment by vatterspun** [comment]
> offer a portable version

This program is already portable as settings are saved to the application folder, meaning it can be run from a USB drive, cloud service, or backup drive with the same settings every time.

**Comment by RoyiAvital** [comment]
How can it be portable and offer Context Menu?
Aren't those driven by Registry Keys?

Portable means no Registry Tracks as well.

Thank You.

**Comment by Bioruebe** [comment]
UniExtract itself only creates registry keys if you enable the context menu entries. Just keep it disabled and there shouldn't be any tracks. 
However, i cannot guarantee no registry keys leftover after running UniExtract, because basically UniExtract uses a different extractors for different file types. This means while a zip extraction can be fully portable, unpacking an exe file might actually leave some traces on the system. (It shouldn't happen very often, but it's possible.)

Also, if the UniExtract has no write permission to its directory (e.g. when it is installed in the program files directory), the %appdata% folder is used to store settings. If you want to run it in a portable mode, make sure it lays somewhere else.

**Comment by vatterspun** [comment]
> i cannot guarantee no registry keys leftover after running UniExtract, because basically UniExtract uses a different extractors for different file types

Precursors to UniExtract2 had similar issues; they rely on a lot of externally developed programs so zero registry writes probably isn't possible.  It could be put inside a wrapper program like YaP, WinPenPack, or PortableApps that will zap all registry entries on program close but that may not be the best use of the dev's time.

> How can it be portable and offer Context Menu?  Aren't those driven by Registry Keys?

Yeah Context Menu options (on any program) aren't portable.  But I wouldn't want a feature useful to many users to be removed in the name of being more stealth.  Portablefreeware has a note on their entry about this: http://www.portablefreeware.com/index.php?id=2764

**Comment by RoyiAvital** [comment]
I can leave with the policy that as long as I keep the right Menu Integration disabled no registry keys are used.

I hope someone at PortableApps will upgrade the current UniExtract to this one.

Thank You.

**Comment by vatterspun** [comment]
PortableApps has traditionally ducked programs like Universal Extractor (the project manager [didn't have nice things to say about it](http://portableapps.com/comment/225069#comment-225069) less than a year ago), but Bioruebe has taken the concept much further and added a lot more functionality.  That might change some minds.

**Comment by djohns451** [comment]
How about emulated registry keys that bypass features that don't make sense in a portable version?

**Comment by djohns451** [comment]
In my fork, specifically in the [portable](https://github.com/djohns451/UniExtract2/tree/portable) branch, there is beginning work on a portable version.

**Comment by vatterspun** [comment]
> In my fork, specifically in the portable branch, there is beginning work on a portable version.

@djohns451 Is there any chance we could talk you into collaborating with @Bioruebe on UE2?  There are already quite a few Universal Extractor forks.

**Comment by djohns451** [comment]
You could, @vatterspun. When it reaches a suitable degree, I plan on creating a pull request of the changes, merging them into their fork.
