### ISSUE TITLE
No context menu (RC3)

### ISSUE THREAD

**Issue by hgdagon** [Bioruebe/UniExtract2#200]
When I select simple, no items are added. When I select cascading, "Universal Extractor" shows up with an arrow next to it, but hovering my cursor over it does not open a submenu.

**Comment by vatterspun** [comment]
As a workaround, you can set it up via the SendTo menu, which I prefer https://www.howtogeek.com/howto/windows-vista/customize-the-windows-vista-send-to-menu/

**Comment by hgdagon** [comment]
Yes, I could, if I knew the arguments UniExtract2 offers. Also, I'm just reporting the issue. I've already made my own changes.

**Comment by hgdagon** [comment]
Latest nightly update fixed the issue for me.

**Comment by Bioruebe** [comment]
I'm glad to see that it works now. Thanks for reporting the bug :+1:
