### ISSUE TITLE
Ransomware Alert after installation last version

### ISSUE THREAD

**Issue by JadranR** [Bioruebe/UniExtract2#214]
Please, check your app. After installation Grisinsoft Anti malware report Alert (please, see attached JPG picture).

With respect,
Jadran Rudec

![Ransomware Alert](https://user-images.githubusercontent.com/53031490/91269464-777c9800-e777-11ea-9c97-822d726b1da2.jpg)

**Comment by Bioruebe** [comment]
I contacted GridinSoft. Should be fixed with the next update of your anti-malware.

**Comment by JadranR** [comment]
Thanks for information :-))

Best Regards,
Jadran

**Comment by JadranR** [comment]
Hello, I send you now updated Frhed translation without issues. (Settings for PoEdit was changed and checked all strings). Please, extract ZIP Archive.

With respect,
Jadran
[Frhed.zip](https://github.com/Bioruebe/UniExtract2/files/5145597/Frhed.zip)

**Comment by Bioruebe** [comment]
> Hello, I send you now updated Frhed translation without issues. (Settings for PoEdit was changed and checked all strings). Please, extract ZIP Archive.

I think you posted this to the wrong repository. I have nothing to do with Frhed ;)

**Comment by JadranR** [comment]
Hi,
Sorry for mistake :-((
With respect
Jadran

V V pon., 7. sep. 2020 ob 17:59 je oseba William Engelmann <
notifications@github.com> napisala:

**Comment by Bioruebe** [comment]
No problem, just wanted to let you know, so you can post it to the right place.
