### ISSUE TITLE
ffmpeg update site gone

### ISSUE THREAD

**Issue by AmyRose1288** [Bioruebe/UniExtract2#227]
---------------------------
Universal Extractor Updater
---------------------------
The file https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.zip  could not be downloaded. Please ensure that you are connected to the internet and try again.
---------------------------
确定   
---------------------------

new link:
https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.zip or https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

**Comment by Bioruebe** [comment]
Thanks for reporting. Fixed.

**Comment by AmyRose1288** [comment]
link fixed (somehow i copied the wrong ones)
