### ISSUE TITLE
Handle MSI with LessMSI

### ISSUE THREAD

**Issue by mirh** [Bioruebe/UniExtract2#23]
https://github.com/activescott/lessmsi

At least in [this case](http://updates.rockstargames.com/patches/eflc/update2_EN.zip) it seems the only thing able to decompress the package. 
Plus, it's FOSS and even actively supported. 

I dunno if then this couldn't supplant all the remainder alternatives.

**Comment by vatterspun** [comment]
The license appears compatible with Universal Extractor 2, however it is standard copyright: https://github.com/activescott/lessmsi/blob/master/LICENSE and doesn't specifically mention how the source is to be handled.

**Comment by vatterspun** [comment]
Oh and LessMSI uses dotNET 4.0 so computers that don't have that or are otherwise restricted from that toolset for security reasons will not be able to use it.  There may also be issues for Windows XP users now or in the future since Microsoft doesn't release updates to dotNET for that platform anymore.

There's discussion on [reducing or minimizing](https://github.com/activescott/lessmsi/issues/34) this dependency but that's the current status.

**Comment by acook** [comment]
@vatterspun That is literally the MIT License.
http://choosealicense.com/licenses/mit/

**Comment by Bioruebe** [comment]
Cool, the link to the project, license and dependency information. You're making it really easy for me to add new features. Thank you :+1: 

I'm not sure about the other extractors for msi files. Lessmsi works better them all of them (good find @mirh) but keeping some of them for users without .NET 4 makes sense. Maybe adding a runtime check for the installed version with a fallback to the currently used method choice would work best here.

**Comment by mirh** [comment]
Oh, I'm glad somebody even cares for old potato XP d:
Though, if any.. Would it be possible to just show this when NET is available, otherwise the old tools?

**Comment by vatterspun** [comment]
> That is literally the MIT License.

Confirmed.

> Oh, I'm glad somebody even cares for old potato XP d:

* It still has more users than Vista and Windows 8 [combined](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers).  That's not a small number of users.
* Compatibility with older operating systems tends to make programs more compatible with WINE.
* Although the program is already considered portable by virtue of how settings are handled, programs that work on older computers are _more_ portable

**Comment by Bioruebe** [comment]
This is how it works now: A registry check is done to find out if .NET 4 or newer is installed. If it was found, lessmsi is used without any prompt, otherwise the old MethodSelect function is executed.

**Comment by vatterspun** [comment]
> A registry check is done to find out if .NET 4 or newer is installed. If it was found, lessmsi is used without any prompt, otherwise the old MethodSelect function is executed.

Sounds good, thanks.
