### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by rjt-gupta** [Bioruebe/UniExtract2#236]
Heyy!

This project is super cool with awesome features.
Any way to run this on linux apart from wine? or any way to automate this?

**Comment by vatterspun** [comment]
It's a very old test, but the original Universal Extractor that this program is based on does appear to work under WINE: https://appdb.winehq.org/objectManager.php?sClass=application&iId=6121

There are some interesting virtualization tools coming out that let you run Windows programs that appear to be automated in the way I think you're hoping for: https://news.ycombinator.com/item?id=25021261
