### ISSUE TITLE
Unable to Successfully Install a Zip File

### ISSUE THREAD

**Issue by amathews84** [Bioruebe/UniExtract2#237]
This is an android app with a companion Windows module which allows you to unlock your PC via Android phone. \

Here is the playstore link for the Fingerprint Unlock app:
https://play.google.com/store/apps/details?id=ro.andreimircius.remotefingerauth

Here is the direct link to the Windows module which can also be found in the Google Play Store page:
https://drive.google.com/drive/folders/1bktvp0JcJKfE92efgxQlo06ARrMfLDFd

I am unable to install the Windows module.  The files are in fact extracted from the zip file but when I try to pair my Android phone it does not recognize the computer due to the PC not having the requisite Windows module installed.

**Comment by Bioruebe** [comment]
Well, you have to install the software. UniExtract can of course unpack the files, but this doesn't add the required driver to the system. You have to execute the exe file and run the installer normally to make it work.
