### ISSUE TITLE
If Java isn't Available, DMG Extraction Fails

### ISSUE THREAD

**Issue by acook** [Bioruebe/UniExtract2#24]
**Filetype:** Apple DMG "disk image"
**Actual file:** https://github.com/acook/blacklight/releases/download/v0.0.1/blacklight.v0.0.1.dmg

**Error message:**
![2016-08-06 22_22_46-d__downloads](https://cloud.githubusercontent.com/assets/71984/17460277/6600629c-5c24-11e6-9557-5ca3769c37de.png)

**7Zip** seems to be able to extract it just fine on its own:
![2016-08-06 22_24_57-d__downloads_blacklight v0 0 1 dmg_](https://cloud.githubusercontent.com/assets/71984/17460291/ac43bfe2-5c24-11e6-85d2-315a68b52af6.png)
Which makes me wonder why it's trying to use Java. 

**Note:** ~~I actually have Java installed, but it's not in the system PATH. It's possible this is confusing to the UniExtract module detector.~~ (update: This doesn't seem to be the problem)

**Minor tweak:** The error message also has no spacing around the module name, which makes it read poorly, but that should be a simple fix. (update: fixed by #25)

**Comment by acook** [comment]
It looks like @Bioruebe added DMGExtractor last year in commit b88ac1d3754ae6a94faac842559eb93ce2000f2c, was there a reason you didn't use 7zip? 
It's possible that DMGExtractor supports a wider range of DMG formats?

The output for *this particular* DMG is identical between using DMGExtractor and 7Zip. (see below)

![2016-08-06 22_42_28-d__downloads_dmgextractor-blacklight v0 0 1_release](https://cloud.githubusercontent.com/assets/71984/17460341/29c14258-5c27-11e6-87eb-825cf3dc019c.png)

The options as I see them:

1) Remove DMGExtractor and use 7Zip for all DMGs
2) Try DMGExtractor and fallback to 7Zip is Java isn't available
3) Use 7Zip by default for DMGs but if extraction fails fallback to DMGExtractor

What does everyone else think?

**Comment by Bioruebe** [comment]
I extracted some of my test files and it seems like 7z does not only work more reliable, but also supports files which fail to extract with DMGExtractor. All other files had the same output for both extractors. 

At the end I choose option 1 and replaced DMGExtractor completely. Thanks for the tip.
