### ISSUE TITLE
Why does universal extractor need to move extracting file from secondary haard vdrive to temp folder on primary?

### ISSUE THREAD

**Issue by kotenok2000** [Bioruebe/UniExtract2#250]

**Comment by piratesephiroth** [comment]
because that's where the temp folder is located, I suppose

**Comment by kotenok2000** [comment]
Why can't it extract without moving files to tremp folder?

**Comment by Bioruebe** [comment]
You can try to disable `Check for unicode characters` from `Edit` > `Preferences`. This should prevent moving files around, but some extractors might not work correctly.
