### ISSUE TITLE
Nightly update to RC4

### ISSUE THREAD

**Issue by l3xrom** [Bioruebe/UniExtract2#258]
When I applied the update checkbox, the program showed that there is RC4, but I can't find a mention of it anywhere. Is this your job or has someone changed the links? Why isn't RC4 release here?

sorry for my English

**Comment by Bioruebe** [comment]
Yes, it's my job :)
I'm currently working on RC 4, but it's not finished yet. That's why it's not mentioned here.
The nightly version is just a preview for those who want to test it early and help by reporting problems.

**Comment by ImportTaste** [comment]
@Bioruebe I'm running UniExtract2 with a portable launcher. Would you do me a favor and link me where RC4 is directly?

**Comment by Bioruebe** [comment]
Sure! You can find the most recent build [here](https://update.bioruebe.com/uniextract/files/nightly.zip). Or, if your portable setup supports it, use the built-in updater to switch to the nightly version by following [this guide](https://github.com/Bioruebe/UniExtract2#nightly-builds).
