### ISSUE TITLE
"Open folder after extraction" setting is not persistent

### ISSUE THREAD

**Issue by rosstex** [Bioruebe/UniExtract2#26]
For some reason, every single time I extract a new file I have to enter the options and re-check this box. I'm on Windows 10, the latest stable version.

**Comment by Bioruebe** [comment]
Is this bug still present in the current version? It seems to work for me using beta 4, but different systems produce different bugs ;)

**Comment by rosstex** [comment]
Thanks for responding! I've been using the new version for about a week. Unfortunately yes for me, I just ran into this a few minutes ago. I'm on Windows 10 x64. Is there a config file I can modify somewhere?

**Comment by Bioruebe** [comment]
Btw, sorry my answer took so long. Well, better late than no answer at all.

Do the other options work?

The settings are saved in the file UniExtract.ini, which can be found in:
a) %APPDATA%\Bioruebe\UniExtract (if UniExtract has no write permissions for its own directory, e.g. when it lays in C:\Program Files, the settings file is created in %APPDATA%)
b) in the same directory as the exe file (this is only used if a) doesn't exist)

**Comment by rosstex** [comment]
Ah, so the option is currently set to 1 in the same folder as the .exe. But the GUI doesn't seem to recognize it.

I'm running the program from the location where I downloaded it (basically in my Downloads folder), if that could be an issue. I don't see anything in %APPDATA% related to UniExtract.

**Comment by Bioruebe** [comment]
That's very strange...

What about the other options, are they saved/loaded correctly?

Something you could try: 
Delete (or rename/move to keep your configuration) UniExtract.ini, start UniExtract (the first start wizard should appear), set the option again. (This would recreate the ini file, maybe the old one is just broken.)

**Comment by rosstex** [comment]
I've noticed that when I open UniExtract.exe directly, the option is set. When it's opened by me double-clicking an archive, the option isn't set.

**Comment by Bioruebe** [comment]
Interesting, so it must be a command line problem. Seems like you don't have to try what I wrote ;) I'll take a look at the code instead.
