### ISSUE TITLE
Add support for Qt Installers

### ISSUE THREAD

**Issue by DUOLabs333** [Bioruebe/UniExtract2#261]
I tried to use UniExtract to extract [johnny](https://openwall.info/wiki/john/johnny), but it failed. It's a "Qt Installer".

**Comment by core-code** [comment]
this would probably boil down to extracting "qres" files. example attached. a supporting project seems to be here: https://github.com/tatokis/qresExtract
[installer.dat.zip](https://github.com/Bioruebe/UniExtract2/files/7527213/installer.dat.zip)
