### ISSUE TITLE
Signature detected: Inno Setup Setup Data (6.1.0) (u). This is not a supported version.

### ISSUE THREAD

**Issue by ltdeta** [Bioruebe/UniExtract2#264]
The log contains the following message:
> 2021-03-18 20:05:12:248	Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.

[2021-03-18_20-05-14_FAILED_XTInstDE-V8.0.0.1202.exe.log](https://github.com/Bioruebe/UniExtract2/files/6166641/2021-03-18_20-05-14_FAILED_XTInstDE-V8.0.0.1202.exe.log)

**Comment by gvp9000** [comment]
Download and put this file inside bin directory

https://sourceforge.net/projects/innounp/files/

**Comment by ltdeta** [comment]
ok, thanks

**Comment by Bioruebe** [comment]
Thanks for the report, innounp will now be updated via UniExtract's updater.
