### ISSUE TITLE
QuickBMS.EXE program not closing

### ISSUE THREAD

**Issue by vatterspun** [Bioruebe/UniExtract2#27]
Setup: Win7x64

**Steps**:
- Run program on the 5 Minute Break program: http://www.softpedia.com/get/Desktop-Enhancements/Clocks-Time-Management/5-Minute-Break.shtml

**Defect**: QuickBMS.exe still running.

**Screenshot**: http://i.imgur.com/5jrC833.png

**Additional notes**: I found this program still running the next day at 20% CPU utilization.  Only noticed it when running a another CPU-intesive operation.

**Comment by Bioruebe** [comment]
Commit 6bb4caa should fix this specific bug. However QuickBMS might freeze when executing some plugins with big files as input, so this issue stays open for now.

**Comment by vatterspun** [comment]
Confirmed.  This one is fixed, thanks :+1:
