### ISSUE TITLE
Support custom themes

### ISSUE THREAD

**Issue by namazso** [Bioruebe/UniExtract2#271]
I know this isn't strictly meant to be supported since it's an OS modification, but it'd be nice if the program would obey system colors. Currently dialog backgrounds are unconditionally white:
![image](https://user-images.githubusercontent.com/8676443/116446102-e9e9ce80-a856-11eb-8296-f4cf8fdf9491.png)

related: #265

**Comment by JNylson** [comment]
See my [fix ](https://github.com/JNylson/UniExtract2/commit/72441d367ad1aee6f0e33135ca073dfad3917eae)for Windows 10 custom themes

**Comment by Bioruebe** [comment]
> See my [fix ](https://github.com/JNylson/UniExtract2/commit/72441d367ad1aee6f0e33135ca073dfad3917eae)for Windows 10 custom themes

Good work! Thank you.
