### ISSUE TITLE
relative extract path issues

### ISSUE THREAD

**Issue by r3sus** [Bioruebe/UniExtract2#274]
Hello and thanks for the tool.
### Issue 1 - duplicate directories.
I'm sending command `UniExtract\UniExtract.exe obs\InnoSetup.exe`
GUI appears with object as absolute path and destination as relative - `obs\InnoSetup`. 
The result is extracted in `obs\obs\InnoSetup`. That means relative path is based from object directory.
Solutions: 
To set relative path base as cwd.
OR
To change cmd line arguments passing - use absolute path. 
OR 
To remove object directory from relative path - however it leads to next issue:
### Issue 2 - unintended object execution.
Changing the extraction path to `InnoSetup` makes the destination correct, but `InnoSetup.exe` is launched on finish, however it should be `explorer`.
Issue is caused by executable has same name as the extraction directory. The command `obs\InnoSetup` leads to opening explorer in this directory, while `InnoSetup` is same as `InnoSetup.exe`.  
Solution: send command `explorer %extractPath%` instead of `%extractPath%`. 
OR 
Execute with slash - `%extractPath%\`. 
OR
Use absolute path.

Much thanks for the tool - I'm not launching installers anymore.

**Comment by Bioruebe** [comment]
Thanks for finding this bug and providing such a detailed report. This commit should fix the issues.

**Comment by r3sus** [comment]
Thank you! After I started using UniEx from context menu, I had no problems so far.
