### ISSUE TITLE
Uniextract self deletes?!?

### ISSUE THREAD

**Issue by jumpjack** [Bioruebe/UniExtract2#277]
Since some days, as soon as I start unpacking a .exe with uniextract, the uniextract.exe file gets self destructed, disappearing from its folder!
What is it going on? It's RC3.

**Comment by Bioruebe** [comment]
My guess: probably caused by an anti-virus software. UniExtract is suddenly misdetected as malicious and deleted as soon as it starts to do something.

**Comment by jumpjack** [comment]
I don't receive any warning message from the antivirus upon deletion, but I'll check its log.

**Comment by kswartz26** [comment]
It is being deleted by Anti-Virus software. Both McAfee Cybereason flag it and remove it.
