### ISSUE TITLE
Steganography: zip file inside jpg

### ISSUE THREAD

**Issue by benosoqu5** [Bioruebe/UniExtract2#281]
Download this picture:
https://pbs.twimg.com/media/DqteCf6WsAAhqwV.jpg

Inside has a zip and inside a rar and inside html.
Possible for Uniextract to recognize this?

**Comment by Bioruebe** [comment]
> Possible for Uniextract to recognize this?

I don't think so. The way UniExtract is built, it cannot detect any hidden files. It only sees a jpg, nothing more.
But I bet many steganography tools exist, which are specifically made for this use case :)
