### ISSUE TITLE
WiX package extractor requires .NET Framework v2 (or v3)

### ISSUE THREAD

**Issue by aphanic** [Bioruebe/UniExtract2#284]
I was thinking about writing to the thread about outdated extractors but it isn't outdated _per se_.

It's only that the current binary and accompanying managed libraries were built targeting .NET 2 and compatible runtimes for it aren't usually present in recent versions of Windows. I was wondering if it could be updated or tweaked so it runs under .NET 4.

One option would be to add a `.config` file explicitly stating version 4.0 as a supported runtime, like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <generatePublisherEvidence enabled="false" />
    <legacyCorruptedStateExceptionsPolicy enabled="true" />
    <loadFromRemoteSources enabled="true" />
  </runtime>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    <supportedRuntime version="v2.0.50727" />
  </startup>
</configuration>
```

I made a couple of tests and it seems to work as expected. Another one would be to update the binaries to the last (dev) build of the 3.x branch, [v3.14.0.4118](https://wixtoolset.org/releases/v3-14-0-4118/), since it already targets a newer version of the framework. It's from mid-May 2020 and development seems to be [focused on v4](https://robmensching.com/blog/posts/2021/5/17/wix-toolset-v4-preview.0/) at the moment so I'd say it'd be a safe update.

If you choose to go with the later, I'm attaching the relevant binaries to this post for convenience ([dark.zip](https://github.com/Bioruebe/UniExtract2/files/6949231/dark.zip)), I've been using those for a while and haven't encountered any problem so far.

**Comment by Bioruebe** [comment]
Thanks for reporting the problem. I fixed it in nightly by updating to the latest dev build.
