### ISSUE TITLE
default language on startup is chinese 

### ISSUE THREAD

**Issue by madsholme** [Bioruebe/UniExtract2#288]
Just downloaded the app, on first launch the language is chinese, and i dont read chinese so im having a hard time setting it to english.

**Comment by madsholme** [comment]
download a rc1 build same isue.

fixed it by deleting all language in the language folder, and then moving the english.ini from the app root into that folder.

**Comment by Bioruebe** [comment]
Sorry for the trouble, this shouldn't have happened.
The language is set to the Windows system language on first start. Not sure why in your case it is Chinese...

Could you send a log file, please? You can do so by selecting `Give feedback` from the `Help` menu. And write `Issue #288` in the empty text field, so I can find your log. Also use the current version of UniExtract, not RC 1.

**Comment by madsholme** [comment]
i think its becaus my system default is danish, and there is no danish translation? so somehow it defaults to chinese?

**Comment by Bioruebe** [comment]
This might be the reason. And a pretty stupid bug. Thanks for the help, I'll check it!

**Comment by Bioruebe** [comment]
It was indeed a very stupid bug, but now it's fixed :partying_face:

**Comment by madsholme** [comment]
thanks :)
