### ISSUE TITLE
Virus check

### ISSUE THREAD

**Issue by harryray33** [Bioruebe/UniExtract2#290]
I use a fairly old nightly version of Uniextract...I want to update to the latest nightly build but I'm getting a lot of warnings from Virustotal.

Any idea of the reason?

Thanks.

**Comment by Bioruebe** [comment]
I finally had some free time and created a [detailed FAQ section](https://github.com/Bioruebe/UniExtract2/blob/master/docs/ANTI-MALWARE.md) regarding the whole anti-virus issue.
