### ISSUE TITLE
Empty folders always are ignored!!!

### ISSUE THREAD

**Issue by Dragodraki** [Bioruebe/UniExtract2#297]
Everytime UniExtract extracts an archive, it forgets to extract empty folders.
Seems it think they weren't necessary. That causes big problems! Many apps need the empty folders to be present for future files - since the folder structure won't build other case.
Please update UniExtract and make it don't any longer ignores empty folder, but extract them too!

**Comment by Bioruebe** [comment]
Hmm, in general UniExtract should extract everything inside an archive. There might be exceptions for some file types, but most of the time it should create empty folders. Could you provide some sample archives, which are extracted incorrectly?
