### ISSUE TITLE
Update  & suggestion

### ISSUE THREAD

**Issue by mikhoul** [Bioruebe/UniExtract2#3]
You can update innounp.exe from v43 to Version 0.45  ;-) 

I was not sure if your version was portable or has an installation file so maybe in the new release you should make it clearer since the executable is the installer also .

Regards :smile:

**Comment by Bioruebe** [comment]
Thanks for your suggestion, updating innounp is planned for the next beta release.

This version actually is portable (e.g. it doesn't save files to progam files dir), a 'real' installer will be added with the first stable release. Also, the naming has to be changed then to make it distinguishable from other inofficial versions.

**Comment by mikhoul** [comment]
BTW: I've posted here: http://www.portablefreeware.com/forums/viewtopic.php?f=4&t=22469&sid=3a70f8db57cd98858881c823d942dc43&p=78584#p78584 where lot of people where happy to discover your fork. :blush:

**Comment by lorenzogatti** [comment]
Possibly worth supporting: archives and self-extracting executables made by a semi-popular (but a bit old) freeware Japanese compression tool called **DGCA** (http://www.emit.jp/). 
There are a GUI tool (which supports English and other languages) and a command line one, similarly to 7-Zip.

**Comment by AndhikaWB** [comment]
Just a suggestion, using exeinfope or peid will create a registry on HKCU\Sofware\PEiD and HKCU\EXEiPE (doesn't exactly remember the name). Could you make this software fully portable by moving this registry to a file? Just like a PortableApps.com launcher

**Comment by mikhoul** [comment]
@AndhikaWB    Look here it's done I think: http://www.portablefreeware.com/index.php?id=2764

**Comment by AndhikaWB** [comment]
@mikhoul i already tried it, but it still creates a registry when it scan a file using exeinfope (using beta 1 of uni extract 2), haven't tried scan a file using peid (there is no option to switch between peid or exeinfope). Sorry for late reply and my bad english, im indonesian

**Comment by Bioruebe** [comment]
@mikhoul The version at portablefreeware.com _is_ the same as this one, so sadly it doesn't solve the problem.

@AndhikaWB With the current commit I made it a bit more portable, as the registry entries are removed after the file scan. Avoiding them completely seems to be a bit difficult... But at least the traces are now removed (only if the registry keys did not exist before, UniExtract should not delete user settings).

**Comment by AndhikaWB** [comment]
@Bioruebe thanks for the reply, i have a suggestion for you to compress a bit large executable (
especially quickBMS) with Free UPX (bit.ly/1Y4RBId). This can significally reduce the size of an exe. Tested on quickBMS.exe with original file size was 12 MB and after compression with UPX is only 2 MB. And of course you don't need to compress all the executable except QuickBMS.exe because the others are only under 2 MB size

**Comment by fanfan54** [comment]
@Bioruebe Hi, great work! I suggest you to update innounp to the version 0.47 from Sourceforge, if you have time
