### ISSUE TITLE
Inno installer only extracts "Additional files" when extracting cheat engine

### ISSUE THREAD

**Issue by thatsprettygood** [Bioruebe/UniExtract2#302]
I tried to extract a Inno installer, but all I got was the "Additional files".

**Comment by Bioruebe** [comment]
Could you provide a link to the installer you were trying to extract?

**Comment by thatsprettygood** [comment]
I was trying to extract the cheat engine installer.
https://cheatengine.org/
I already fixed my issue by compiling it manually, but the prepacked installer only spits out "Additional files" when extracted.

**Comment by Bioruebe** [comment]
After looking into this I can say: the reason UniExtract does not extract anything is that there are no files to extract. It's a web installer, which downloads them as needed when it's run. There's no easy way to support these kind of installers at the moment, so I guess we're out of luck for this file.
