### ISSUE TITLE
Add option to disable tray

### ISSUE THREAD

**Issue by Mitch037** [Bioruebe/UniExtract2#304]

**Comment by Bioruebe** [comment]
Do you mean the tray icon? The status box can already be disabled from the options. The tray icon is always visible at the moment, because it didn't annoy anyone so far ;)

**Comment by Mitch037** [comment]
It would be a small but useful feature to have the ability of enabling/disabling the tray icon.

**Comment by Bioruebe** [comment]
OK, that should be pretty easy to do. I'll add an option to disable it.
