### ISSUE TITLE
Inno 6.1.0 does not work with UniExtract2 RC3

### ISSUE THREAD

**Issue by BlohoJo** [Bioruebe/UniExtract2#309]
Once again Inno was updated, and the update does not work with Universal Extractor.

```
Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.
```

**Comment by giuenara** [comment]
Is there a solution for this?

**Comment by BlohoJo** [comment]
Most of the files I extract use Inno, and most everything I work with is now at Inno 6.1.0, so, with no update to support it, Universal Extractor has become all but useless for me. :(

**Comment by Bioruebe** [comment]
Please use the [RC 4 nightly version](https://github.com/Bioruebe/UniExtract2#nightly-builds) and most Inno Setups should extract fine.
