### ISSUE TITLE
Last UniExtract with old version of Demoleition

### ISSUE THREAD

**Issue by AEROBATlCS** [Bioruebe/UniExtract2#315]
Hi. In your package demoleition version is 0.61
Now last version from Dec 2021 is 0.65
Recomment to add latest version of demoleition.
https://disk.yandex.ru/d/fxMLnf82zIUADA
Version 0.65 last 8 zero symbols in the end of file.
BRGDS

**Comment by vodek3** [comment]
Molebox 2.x unpacker (De-Mole-Ition) home page
https://lifeinhex.com/update-of-unpackers-2/
Version 0.65 link:
https://mega.nz/file/B0wWCDbZ#64t_VeMTnCtZ7yB6z46YV7TBRNFS2Hjxl_6ftn6B9tM

**Comment by AEROBATlCS** [comment]
I have 0.65 version. It is for this reason that I am writing to you.
I'm just informing you that in your allegedly fresh assembly there are old components that do not work quite correctly.

**Comment by vodek3** [comment]
Have you tried updating Universal Extractor? Sometimes it helps.
I will teach you how to get De-Mole-Ition 0.65 in two steps.
Делай раз:
![image](https://user-images.githubusercontent.com/25941601/163977440-4b8c6905-9d29-4695-92d4-77aff2687aa7.png)

Делай два:
![image](https://user-images.githubusercontent.com/25941601/163977566-dfc28984-d267-4fde-9eb9-2f4a7e515fc5.png)

Клац и расходимся.
![image](https://user-images.githubusercontent.com/25941601/163978632-582e8f0c-58f0-429f-82ef-610e933fe46e.png)
