### ISSUE TITLE
False Virus Positive?

### ISSUE THREAD

**Issue by Flashfire42** [Bioruebe/UniExtract2#323]
Upon updating to the latest development version windows defender flagged it. 
![image](https://user-images.githubusercontent.com/40415824/181442016-aa235f2c-068a-43f4-b332-938e7dcd06cb.png)

**Comment by AndnixSH** [comment]
Duplicate https://github.com/Bioruebe/UniExtract2/issues/78

**Comment by Bioruebe** [comment]
Defender always does this, for every new version. There's nothing I can do, except sending false positive reports again and again.
