### ISSUE TITLE
MSI Extractor

### ISSUE THREAD

**Issue by Aksam420** [Bioruebe/UniExtract2#33]
Previous beta 3 was working perfect with msi but beta 4 is unable to extract
FoxitPhantomPDF81_Business_enu_Setup.msi
Image is for beta 3
![real](https://cloud.githubusercontent.com/assets/14086097/19711206/791b5996-9b4d-11e6-8961-8c7a992c0534.jpg)
Image for beta 4
![crop](https://cloud.githubusercontent.com/assets/14086097/19711221/91e64a26-9b4d-11e6-8c52-66750d46d06f.jpg)

**Comment by mirh** [comment]
Does it extract normally with standalone [LessMSI](http://lessmsi.activescott.com/)?

**Comment by DjDiabolik** [comment]
Yeah............ i have also send two or more feedback..... beta 4 no more extract msi files........ on previous beta 3 all working whitout a problems after the prompt.

I have tryed to extract latest build of VirtualDj 8 install_virtualdj_pc_v8.2.3456.msi

**Comment by DjDiabolik** [comment]
I my case the LessMSI works for VirtualDJ msi...............

**Comment by Aksam420** [comment]
Yes working with less msi
![gg](https://cloud.githubusercontent.com/assets/14086097/19824725/7cc14f7a-9d8b-11e6-974e-34a8015b369d.jpg)

**Comment by Bioruebe** [comment]
There was a small problem executing lessmsi when UniExtract's lays inside a path containing spaces. Beta 4b is available now.
