### ISSUE TITLE
newest nightly version, detected as malware :(

### ISSUE THREAD

**Issue by zedd-0** [Bioruebe/UniExtract2#334]
https://www.virustotal.com/gui/file/1c8af2b581da99e3289bd404159b477109e1fd8e4f1a08d7900321ba18d4a201/detection

the newest version of UniExtract.exe is detected as a malware :(
tested with windows defender.

**Comment by thatsprettygood** [comment]
Is this ever going to be addressed?

**Comment by maboroshin** [comment]
https://github.com/Bioruebe/UniExtract2/issues/78

**Comment by Bioruebe** [comment]
Interesting observation, @arix00
I did a couple of tests during the last weeks, but no solution yet. `3.16.0` has some bad bugs, so I can't use it. I went back to `3.3.14.x`, but still getting 11 detections. So annoying...

**Comment by Bioruebe** [comment]
Doesn't change much, it's always fine after compilation, but quickly goes back to ~8 detections after a few days. No matter the AutoIt version :(
