### ISSUE TITLE
Does file extension matter? 

### ISSUE THREAD

**Issue by gmgunderground** [Bioruebe/UniExtract2#349]
Does input file extension is it important for uniextract to choose the type of unpacking algorithm?

**Comment by Bioruebe** [comment]
For most files it doesn't matter. The actual file content is used to determine how to unpack. Only if this fails, the extension is taken into account. An exception are very few file types (mostly disk images such as `.bin`, `.iso`, `.mdf`), which cannot be recognized reliably by their content. Those files *might* not extract, if the extension is wrong or missing.
