### ISSUE TITLE
Smart Install Maker 5.04 extractor

### ISSUE THREAD

**Issue by skarsgal** [Bioruebe/UniExtract2#35]
Hi,
in Your recent build 'Universal Extractor 2 v2.0.0 Beta 4' there is not the file 'sim_unpacker.exe' for extract from installers created with Smart Install Maker http://www.sminstall.com/ .
This unpacker is present inside build of Joo Seng (see this topic http://forum.portableappc.com/viewtopic.php?f=4&t=386&p=4877&hilit=gora#p4877 ).
Do You can add this unpacker in next build ?
Thanks

**Comment by Bioruebe** [comment]
Sorry, but sim_unpacker is not licensed under any open source license (afaik), so for legal reasons I cannot distribute it as part of UniExtract. You can easily download it on your own using the help menu > plugins > Smart Install Maker unpacker by clicking the download button, saving the file to a directory of your choice. Then, click 'Select file' and search for the file you just downloaded. UniExtract can now unpack Smart Install Maker installers.
