### ISSUE TITLE
Can't Extract Some InnoSetup Installers

### ISSUE THREAD

**Issue by bc-185** [Bioruebe/UniExtract2#353]
The included `innounp` extractor cannot extract some InnoSetup installers, such as [this one](https://github.com/Querz/mcaselector/releases/download/2.1/MCA_Selector_Setup.exe). This appears to be an issue with an outdated extractor, since it is possible to work around this issue by updating the included `innounp.exe` to version 0.50.

**Comment by GitHubRulesOK** [comment]
hmm my version includes November version 50 so perhaps check your update settings in preferences mine is set to weekly.

**Comment by Bioruebe** [comment]
Please use the [nightly version](https://github.com/Bioruebe/UniExtract2#nightly-builds), it's fixed there.
