### ISSUE TITLE
VirusTotal detection Report

### ISSUE THREAD

**Issue by wonkawilly** [Bioruebe/UniExtract2#361]
Please check this out, it is worrying:
https://www.virustotal.com/gui/file/03170680b80f2afdf824f4d700c11b8e2dac805a4d9bd3d24f53e43bd7131c3a
9 security vendors and no sandboxes flagged this file as malicious

![image](https://github.com/Bioruebe/UniExtract2/assets/34818345/ba2293d0-7e5a-4f20-bbbe-bc280e14fab5)

**Comment by atylo** [comment]
Only 8 out of 59 (by now), and not very popular nor sophisticated antivirus programs detect something malicious in this entire archive, and even then some of them just say it's a suspicious PE or a possible threat. Read something about false positives, it's usually one of those.
