### ISSUE TITLE
How to download v2.0.0 RC 4

### ISSUE THREAD

**Issue by kiwichick888** [Bioruebe/UniExtract2#365]
Am I missing something? The changelog page says the latest version is 2.0.0 RC 4 (2023) but the version downloaded by clicking the Download button is still version 2.0.0 RC 3. Is RC4 not actually available for download yet?

**Comment by AllanHigdon** [comment]
I have no idea why the Download link hasn't been updated to RC4.
You can update to RC4 through the program itself, using the "Install beta updates" option.
You can also download the current development build at https://update.bioruebe.com/uniextract/files/nightly.zip

**Comment by thunderpants** [comment]
So i presume the updater.exe ,set to beta, will download newer files only ?

**Comment by Wisewiz001** [comment]
It's also available at this link: 
https://www.neowin.net/software/universal-extractor-2-uniextract2-200-rc4/
And no, it doesn't do the newer-files-only thing. Just delete your RC3 files and put your RC4 files in their place.

**Comment by raddyst** [comment]
> It's also available at this link: neowin.net

The same update.bioruebe.com/uniextract/files/nightly.zip

> Just delete your RC3 files and put your RC4 files in their place.

For what? Updater sync your uniextract automatically.

**Comment by Wisewiz001** [comment]
Interestingly, the updater in RC4 tells you that a newer version is available, and then gets RC3. I'm not sure the RC3 updater will get you RC4.

**Comment by raddyst** [comment]
> Interestingly, the updater in RC4 tells you that a newer version is available, and then gets RC3. I'm not sure the RC3 updater will get you RC4.

Maybe you uncheck "Install beta updates" in Preferences.
