### ISSUE TITLE
Legacy InstallShield: View Files?

### ISSUE THREAD

**Issue by lmstearn** [Bioruebe/UniExtract2#368]
Hi!
This is really just a thank you for the beautiful program. :thumbsup:
The old InstallShield builds offered _iscabvu_ to see the contents of an archive without extracting them. Would work very well in conjunction with the scan report, which is really nice.
Having already extracted the files from [BGTalesUS5512.exe](https://www.gibberlings3.net/files/file/901-official-patches-baldurs-gate/) with 7zip, (7zip could not read the cab file obviously), UniExtractor successfully extracted the files in _data1.cab_ when _**data1.hdr**_ was specified in the dialog. If instead, _data1.cab_ is used, there is an error.
Posted through UE feedback the details, and cross-linked this post. It's evident to me that if the parent archive _BGTalesUS5512.exe_ was specified in the dialog, there would be no problem. As it is, this is more of a feature request than an actual problem,
Thanks! :smile:

**Comment by GitHubRulesOK** [comment]
I dont think the older iscab vu can handle those files I tried your bgtales exe after UE expanded to a folder on the 3 cabs and their hdrs and all 6 files show ed
![image](https://github.com/Bioruebe/UniExtract2/assets/12754913/a0cd713c-901e-4a51-8268-056c714ca023)
 so it should have been same era that is v6 2000 should have understood 1999 V5 
![image](https://github.com/Bioruebe/UniExtract2/assets/12754913/6cf8b8fd-02b3-4c7b-8381-36101b97affe)
 but looks like the cabs were incompatible v5

**Comment by lmstearn** [comment]
Yes, weird that v5 `iscabvu` works, and v6 is not backward compatible.

**Comment by GitHubRulesOK** [comment]
I dont have a 5 vu but that utility was advanced/good in its day but after it got sold like many apps it goes downhill from thereon and VU was AFAIK dropped after version 6

**Comment by GitHubRulesOK** [comment]
OK found the 5.5 iscabvu (seems it was the earliest version available and more recently replaced by iscabview.exe) but I dont think its much use it needs a installshield install to function and then for your target BG55.exe whilst it does confirm where files should be subject to folders, there are possibly easier methods like install in a VM
![image](https://github.com/Bioruebe/UniExtract2/assets/12754913/3beb936a-9065-4603-9c31-d85877c0484c)
