### ISSUE TITLE
RC4 'Newest Nightly' is Identified as (Trojan:Win32/Sonbokli.A!cl) and deleted

### ISSUE THREAD

**Issue by TempAccountNull** [Bioruebe/UniExtract2#370]
- This Affects both Windows 10 & 11.

# Versions: Affected: 2.0.0 RC 4 (15.10.2023)
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/88ab5e1d-6733-4aca-9bfb-bff742b89126)

# Running the Application
The Application is fine to run without updating by this [link](https://github.com/Bioruebe/UniExtract2#download)

However: If you've already updated:
- The File `UniExtract.exe` will be **removed** on loading windows.
- If it hasn't already been detected, it will be eventually get scanned and **removed** as it was false identified as a `trojan`.

# How to Reproduce:
1. Download the above link by clicking "link"
2. Run the older RC3 build and Upon running it, you will be asked to update 
3. Update and let it finish updating to the newest nightly
4. `UniExtract.exe` will immediately be deleted and the user is shown the following.
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/606dca79-9969-4e1d-93c3-65acae5458e3)

# Threat Detection Statistics: 
Type: Trojan:Win32/Sonbokli.A!cl
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/c6b67a30-2166-4e35-a3ad-26e76d4138d2)

# To get around this in the mean time:
-  You will have no choice but set an exclusion in your antivirus settings.
## To do this:
1. Hit Windows key and type "virus" click 
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/af61ddd4-6699-4dc0-83cc-37887080e3a8)

5. Click manage settings
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/d09b5bd9-5ff6-421e-8356-911ba72040a0)

6.Scroll down to Exclusions
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/1eaf61f4-6dfc-4bfc-a81e-fe4e0a5d5953)

7. Click add or remove exclusions and hit yes on the UAC prompt.
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/7e5dc906-6a9e-46ad-9eba-5e6e520c8aa8)

8. Click Add an exclusion
![image](https://github.com/Bioruebe/UniExtract2/assets/11286901/51cb4d64-44a1-4ccf-8c9e-7afecaf2b3d3)

9. Select the location of your folder and it won't scan it again.
10. Re-download and extract to that folder only then run and update it.

**Comment by Bioruebe** [comment]
Should be fixed now.
