### ISSUE TITLE
Improve detection of exe installer

### ISSUE THREAD

**Issue by superbonaci** [Bioruebe/UniExtract2#377]
The sample installed can be downloaded here:
https://dl2.plm.automation.siemens.com/jt2go/installer/JT2Go.zip

It opens the installer and tries to install the programs which is not what I want.

**Comment by raddyst** [comment]
> It opens the installer and tries to install the programs which is not what I want.

Try https://github.com/lifenjoiner/ISx

`0x0404.ini
0x0405.ini
0x0407.ini
0x0409.ini
0x040a.ini
0x040c.ini
0x0410.ini
0x0411.ini
0x0412.ini
0x0415.ini
0x0416.ini
0x0419.ini
0x0804.ini
1028.mst
1029.mst
1031.mst
1033.mst
1034.mst
1036.mst
1040.mst
1041.mst
1042.mst
1045.mst
1046.mst
1049.mst
2052.mst
JT2Go.isc
JT2Go.msi
jt2gosetup_ext.bin
jt2gosetup_sfx.exe
Setup.ini
Visual C++ 2015 - 2022 Redistributable (x64).prq
VS2022.vc_redist.x64.exe
WindowsInstaller-KB893803-x86.exe`

**Comment by superbonaci** [comment]
Yes but I can't continue the extraction: https://github.com/lifenjoiner/ISx/issues/12

**Comment by raddyst** [comment]
> Yes but I can't continue the extraction: [lifenjoiner/ISx#12](https://github.com/lifenjoiner/ISx/issues/12)

ISx = **InstallShield** installer extractor only., JT2Go.msi (Microsoft Software Installer) you can unpack with UniExtract2.

JT2GoSetup_sfx.exe is not packed, use "disassembler" if you really need.

![image](https://github.com/Bioruebe/UniExtract2/assets/8584929/89ed288c-b9a9-461e-8b0b-6116a7a82940)

ps. https://github.com/lifenjoiner/ISx/issues/12 - better to close this issue.

**Comment by superbonaci** [comment]
With [ISx](https://github.com/lifenjoiner/ISx) extract `JT2GoSetup.exe` then with UniExtract2 extract `JT2Go.msi`, and its the `C:\Program Files 64\` files are there.
