### ISSUE TITLE
Add support for extracting clickteam installers.

### ISSUE THREAD

**Issue by kotenok2000** [Bioruebe/UniExtract2#382]
It can't extract files from this file
https://www.moddb.com/mods/point-of-view/downloads/point-of-view-11

**Comment by Wisewiz001** [comment]
No, it can't. It comes up with "unknown file type." I don't think UniExtract2 is to blame here. I think the pov.exe file is malformed for an installer. I watched UniExtractor try every method in its arsenal, and it couldn't make sense of pov.exe. If UniExtract2 works on standard installation executables perfectly well, but fails on non-standard ones, I don't think UniExtract is at fault.

**Comment by raddyst** [comment]
> It can't extract files from this file
> https://www.moddb.com/mods/point-of-view/downloads/point-of-view-11

Maybe better write in https://github.com/Bioruebe/cicdec , but [similar question](https://github.com/Bioruebe/cicdec/issues/5) is unanswered.

**Comment by kotenok2000** [comment]
I already did it.
https://github.com/Bioruebe/cicdec/issues/9

**Comment by Bioruebe** [comment]
Closing this issue in favor of https://github.com/Bioruebe/cicdec/issues/9
I'll take a look when I have time to work on cicdec again.
