### ISSUE TITLE
Earth Defense Force 5 EXE support request

### ISSUE THREAD

**Issue by MaybeBirb** [Bioruebe/UniExtract2#383]
Hi, I'm from the EDF 5 modding community. I notice your tool can indeed extract EDF5.EXE (the main game file), but not in any readable format before it crashes and self-terminates with no explanation from the log. We've been attempting to mod Earth Defense Force 5's EXE for a long time, and I would love to have support added for it!

**Comment by raddyst** [comment]
Maybe you upload or post link for  EDF5.EXE?

**Comment by raddyst** [comment]
> EDF5.zip

This file is not packed.

![image](https://github.com/Bioruebe/UniExtract2/assets/8584929/7bfcedfe-a2b1-41d6-b4a3-4f113d84edbf)
