### ISSUE TITLE
How to create an executable .exe file?

### ISSUE THREAD

**Issue by grsrse** [Bioruebe/UniExtract2#389]
I faced such a problem when I changed files after unzipping with UniExtract2, and then I don't know how to put everything back together. I tried to create an executable SFX-archive using WinRAR built-in function. But then I found out that it creates an installation file which I don't need, but I need an .exe executable file. If what I edited, I was editing The Elder Scrolls IV: Oblivion launcher.

**Comment by Bioruebe** [comment]
I guess you found the answer yourself, but for anyone else looking at this issue: repacking is not supported ans i don't plan on adding this functionality. See the [FAQ](https://github.com/Bioruebe/UniExtract2?tab=readme-ov-file#can-uniextract-recompress-files) for more information.
