### ISSUE TITLE
Exeinfo PE crashes computer when used to identify file type

### ISSUE THREAD

**Issue by IvanDrag0** [Bioruebe/UniExtract2#393]
When trying to extract a file type that UniExtract2 isn't able to extract, it launches Exeinfo PE to try to analyze the file. The current version causes many instances of exeinfope.exe to spawn, causing the computer to come to a halt.

**Comment by raddyst** [comment]
> The current version causes many instances of exeinfope.exe to spawn, causing the computer to come to a halt.

Do you use RC3 or RC4 (beta) version?

**Comment by IvanDrag0** [comment]
RC3. Should I try RC4?

**Comment by raddyst** [comment]
> Should I try RC4?

Of course.

**Comment by IvanDrag0** [comment]
Just tried and looks like it's being flagged as a virus. I opened another [issue](https://github.com/Bioruebe/UniExtract2/issues/394) about it.

**Comment by IvanDrag0** [comment]
Issue seems to be resolved in the latest beta (RC4). Thank you!
