### ISSUE TITLE
Windows Defender flags UniExtract.exe RC4 as a virus

### ISSUE THREAD

**Issue by IvanDrag0** [Bioruebe/UniExtract2#394]
Windows Defender (and looks like [several](https://www.virustotal.com/gui/file/3ea243da0859051c8f2d5e4f0e62b1cbe15dc560256194103605db112c4c866c) others) flag the UniExtract.exe RC4 file as a virus, preventing me from being able to update RC3.

**Comment by raddyst** [comment]
Anti-Malware false positives
https://github.com/Bioruebe/UniExtract2/issues/78

**Comment by Wisewiz001** [comment]
It’s just not known by WD.  Add it to your exceptions, and try again. I’ve been using it for years now, and I’ve had zero problems.
