### ISSUE TITLE
Cannot extract files from ElevenClock version 4.4.0 installation executable

### ISSUE THREAD

**Issue by 03302024** [Bioruebe/UniExtract2#396]
ElevenClock (https://github.com/marticliment/ElevenClock) version 4.4.0 installation executable at (https://github.com/marticliment/ElevenClock/releases/download/4.4.0/ElevenClock.Installer.exe) cannot be extracted.

**Comment by raddyst** [comment]
Use [Windows InnoUnpacker](https://www.rathlev-home.de/index-e.html) for this,
or replace bin\innounp.exe with https://github.com/jrathlev/InnoUnpacker-Windows-GUI/raw/master/innounp-1/bin/innounp-172.zip and forget about Universal Extractor automatic updates.

**Comment by 03302024** [comment]
> replace bin\innounp.exe with innounp-172.zip

Great, thank you! 
Now, I know how to manualy update those unpacker files.

**Comment by raddyst** [comment]
> Now, I know how to manualy update those unpacker files.

But if you use automatic update, old version will return.

**Comment by 03302024** [comment]
OK, thanks for the info. I won't use auto update or will recopy files after an update.
