### ISSUE TITLE
No instructions for adding external plugins

### ISSUE THREAD

**Issue by FredThompsonII** [Bioruebe/UniExtract2#4]
Need instructions for adding external plugins.

Assume they are supposed to go into bin directory but:

Link for RPGMaker Decrypter is down.

crass/cage - crage.exe isn't recognized as being installed
h4sh3m download file is passworded - what is password? link is to persiangig
MPQ plugin - which files are used? assume mpq.wcx ListFile.txt
RPGMaker Decrypter link is down

**Comment by Bioruebe** [comment]
Thanks for the report, confirmed the problems.
Maybe auto-downloading or at least importing should be added to make it clearer.

Password is h4sh3m
mpq.wcx is the only file needed for MPQ support
crage path needs to be bin\crass-0.4.14.0\crage.exe
I don't have a replacement link for RPGMaker at the moment, will follow
This will probably change in one of the next versions
All files need to be in \bin directory
