### ISSUE TITLE
How to use UniExtract2?

### ISSUE THREAD

**Issue by jeffrey008** [Bioruebe/UniExtract2#41]
Hello, I am new here. I wonder how can I use UniExtract2? I saw no .exe file in repo, and the repo is mainly config file. Where should I start if I want to help maintain this application? Thanks.

**Comment by acook** [comment]
@jeffrey008 https://github.com/Bioruebe/UniExtract2/releases

**Comment by jeffrey008** [comment]
@acook oh thank you every much! How silly I was. Should we add something in readme to let people know where the soucre and executable are? I can make a PR if you want.
