### ISSUE TITLE
Crash with installshield

### ISSUE THREAD

**Issue by mirh** [Bioruebe/UniExtract2#42]
When you try to extract the setup.exe file contained inside [this](http://twdl.cyberlink.com/ftpdload/Patch/CyberLinkBD/HDAdvisor/CDT140213-01/TR140310-017/BD_3DAdvisor_7510_Generic_BD_CDT140213-01.exe).

**Comment by vatterspun** [comment]
What are you talking about?

**Comment by mirh** [comment]
UniExtract2 crashes when extracting aformentioned file. 
What cannot be understood?

**Comment by vatterspun** [comment]
> What cannot be understood?

Usually when people submit a crash report, it includes steps to reproduce.  Could you walk us through the steps that you took to get to that?  Did you uniextract the _BD_3DAdvisor_7510_Generic_BD_CDT140213-01.exe_ file and then uniextract a file it creates?

Thanks.

**Comment by mirh** [comment]
... 
God, sorry. I dunno what I was thinking. 
Yes, indeed it's not directly that file, but the setup.exe contained inside. 

And it doesn't even seem UniExtract specific. 
It's `quickbms.exe  -l InstExpl.wcx Setup.exe` that crashes. 

I'd close this and report to aluigi then, but for the love of me I cannot register on the [bug](http://zenhax.com/viewtopic.php?f=13&t=556) site.

**Comment by mirh** [comment]
So.. Aluigi kind of said he won't spend any more time into total commander plugins...
This means we'd need a different tool for this file. 
Which I guess leads us to #46. But I'm not sure so I'll still leave this open.

**Comment by lifenjoiner** [comment]
@mirh
I have just tested the file you mentioned. It can be recognized and extracted by 7-zip (v16.04).
It is recognized as 'InstallShield AFW [Overlay]' by PEiD and 'CAB/7z/Zip, Overlay' by exeinfope.

**Comment by mirh** [comment]
I know. 
As I said, it's the setup.exe contained inside (that you get by first extracting with 7-zip, yes) that give problems.

**Comment by lifenjoiner** [comment]
The 'setup.exe' that extracted is just a stub/launcher, as I know. You can use 'ISCab' on the cab file volumes.

**Comment by mirh** [comment]
*Yes*
But \*nonetheless\* it shouldn't **crash**. Tell me I'm dumb for trying to look at the wrong file, error, ok - fine.. But no "this program has stopped working" message.

**Comment by Bioruebe** [comment]
Seems like the crash doesn't happen with the current version of UniExtract.
