### ISSUE TITLE
"Context Menu Entries" window doesn't detect Windows Server 2016 for cascading menus

### ISSUE THREAD

**Issue by enfiniti27** [Bioruebe/UniExtract2#47]
I'm running 2.0 beta 4 on Server 2016 and tried to get cascading menus working but it is greyed out. The tooltip says you need Windows 7 or higher. This might be the same on Windows 10 as well.

**Comment by vatterspun** [comment]
Screenshot?

**Comment by enfiniti27** [comment]
![uniextractcascade](https://cloud.githubusercontent.com/assets/25395153/22390485/4862e214-e4b9-11e6-9762-b1decbeed42f.png)

**Comment by enfiniti27** [comment]
Thanks!
