### ISSUE TITLE
Parse NSIS installers to fix folder names

### ISSUE THREAD

**Issue by djohns451** [Bioruebe/UniExtract2#65]
A sample installer, the [Unity Standard Assets](http://netstorage.unity3d.com/unity/497a0f351392/WindowsStandardAssetsInstaller/UnityStandardAssetsSetup-5.6.0f3.exe?_ga=1.247318788.1866946384.1493124572) installer, exports to a specific folder. It would be helpful if the generated NSIS script was parsed, and extracted folders were renamed accordingly.

**Comment by Bioruebe** [comment]
Parsing the installer script sounds like an easy thing to do, but the purpose of using a script is to set the directories dynamically, i.e. based on user input. This basically means the only way to get the paths is running the script (or simulating it), which would be a lot of work without much gain and likely add a load of security holes.

So sorry, but that's out of scope for UniExtract.
