### ISSUE TITLE
unrpa 1.4.2 out - fixed all my problems

### ISSUE THREAD

**Issue by hairypaulsack** [Bioruebe/UniExtract2#67]
I had been having 100% failure rate with unrpa. I rebuilt 1.4.1 and placed in /bin/unrpa/ and it still failed. now that this new version 1.4.2 is out, I built with python 2.7.13 and replaced the files in /bin/unrpa and it works again! Maybe this can save you some time, thought I figure you'll probably want to build it yourself

this is 1.4.2
[unrpa.zip](https://github.com/Bioruebe/UniExtract2/files/1023777/unrpa.zip)

**Comment by Bioruebe** [comment]
Thanks for your work, the new version will be added with the next update.
