### ISSUE TITLE
Don't include complied executables

### ISSUE THREAD

**Issue by softwarespot** [Bioruebe/UniExtract2#7]
This is bad practice and makes the repository quite large. Compiled executable should be for releases only.

By the way I am an official AutoIt developer, so applaud that you're continuing with this project. I also see you took inspiration from quite a few of my ideas

**Comment by Bioruebe** [comment]
Hmm, I don't even know why it is in repository... At least there is a simple solution to this issue :)

Thank you, if you have more ideas feel free to tell me :+1:

**Comment by RoyiAvital** [comment]
What about a portable version?
