### ISSUE TITLE
Timeline: New release planned? When?

### ISSUE THREAD

**Issue by myfairsyer** [Bioruebe/UniExtract2#72]
Reword it however you like, I'm just moving this to an own issue as in #70 @MelchiorGaspar told he didn't know where to put it. :)

So are there any further releases foreseeable?
Is there any plan?
Thanks

**Comment by MelchiorGaspar** [comment]
ok...
"any chance you will be getting another beta out sooner or later?" - MelchiorGaspar

**Comment by DjDiabolik** [comment]
To many users have make same question............ no answers.......... i thinks simply no.

**Comment by DjDiabolik** [comment]
https://github.com/Bioruebe/UniExtract2/issues/45 it's a 3jan request...

**Comment by MelchiorGaspar** [comment]
lol.. yeah go figure some one else already asked... ;) 
and IK asking for updates is not always the most popular question with devs ;p 
sry..  xD

**Comment by Bioruebe** [comment]
> It's done, when it's done.

I didn't have much time lately to work on UniExtract, so sorry for the delays. It shouldn't take too long until the next update, but no promises here.

**Comment by MelchiorGaspar** [comment]
no worry take your time thx for taking over and updating UniExtract..

**Comment by acook** [comment]
This is basically a duplicate of #45.

More useful questions might be: 
- What are the blockers to making a new release?
- How to build the project yourself? What version of AutoIt is required? Anything else needed?

Maybe it'd be nice to include the build instructions in the README?

**Comment by vatterspun** [comment]
@MelchiorGaspar 
> no worry take your time thx for taking over and updating UniExtract.

True.  A lot of forks of this project have come and gone and you've taken it a lot farther than any other.  We're lucky to have you.

**Comment by acook** [comment]
If people are wondering how to build their own version, here is how:

0. Download [AutoIt](https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3.zip) and extract it to a folder (or install it if you got the installer)
1. Download [this repo](https://github.com/Bioruebe/UniExtract2/archive/master.zip) (use git or extract the zip to a folder)
2. Go your your AutoIt folder then into the Aut2exe folder and double click on `Aut2exe_64.exe`
3. Then browse to the folder you put the UniExtract2 source files and select `UniExtract2.au3`
4. Click `Compile`
5. Double click the `UniExtract2.exe` created by step 4

More info on AutoIt's website (with screenshots): https://www.autoitscript.com/autoit3/docs/intro/compiler.htm

**Comment by DjDiabolik** [comment]
@acook and for all bin of extractor ?

**Comment by acook** [comment]
@DjDiabolik Not sure what you mean? You can get all of the extractors with the last release?

**Comment by DjDiabolik** [comment]
yeah... all external extractors...... how i can pick somethigs like an upgraded collection ?

**Comment by timofonic** [comment]
@DjDiabolik 

Would you please make an upgraded pack? Please! :D

Does this fork features recursive scanning, renaming and extracting? It would be amazing!

**Comment by acook** [comment]
Hmm. It does seem like it would be nice to have a script to download all of the extractors. If I have some time to look into that I will see what I can do. 

How should they be versioned?
1. Should we always try to grab the latest
2. or a specific version (in case a newer version breaks something)?

**Comment by jyrkive** [comment]
I'd prefer always attempting to update to the latest version.

**Comment by MaDill** [comment]
Is there any plan to download a new version without compile by my own?

**Comment by DjDiabolik** [comment]
thanks for rc 1...
