### ISSUE TITLE
Windows 10 treats UniExtractUpdater.exe as Trojan:Win32/Rundas.B

### ISSUE THREAD

**Issue by ppeters917** [Bioruebe/UniExtract2#73]
![image](https://user-images.githubusercontent.com/2444631/27897399-6c855ee4-6220-11e7-96a5-8a93d6ad5bc9.png)

**Comment by acook** [comment]
Is this Windows Defender?

**Comment by vatterspun** [comment]
It's a false positive.  See VirusTotal.com:

https://www.virustotal.com/en/file/63530fbddeb0a6c4d2721a8c43956622aa2fb6d856c3fc27e6df4fdd0970e3ae/analysis/

It has a rating of 5 out of 60 and all those are from small time anti-virus programs.

Freeware devs deal with this constantly: http://www.nirsoft.net/false_positive_report.html

**Comment by ppeters917** [comment]
Yes issue is coming from Windows Defender (Windows 10 Pro Insider Preview Build 16232)

**Comment by jyrkive** [comment]
I submitted a false positive report to Microsoft.

**Comment by jyrkive** [comment]
Microsoft addressed the report. Windows Defender no longer treats the updater as malware.

**Comment by Bioruebe** [comment]
Thanks for your efforts.
