### ISSUE TITLE
[suggestion] handling MSI in the new "WiX" format (with example)

### ISSUE THREAD

**Issue by eladkarako** [Bioruebe/UniExtract2#74]
Classic MSI (cab-archive/self extracted exe) is already well supported.
But most of the new installers released by Microsoft <sub>(for example <a href="https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtools_full.exe">VS 2005 build-tools</a>)</sub>
are now in the new <a title="Windows Installer XML Toolset" href="https://en.wikipedia.org/wiki/WiX/">WiX</a> format,
which is not compatible w/ msi2xml or MsiX - there is a <strong>new (and free) tool for it!</strong>

Standard MSI:<br/> <code>msiexec.exe /a archive.msi /qb /l log.txt TARGETDIR="C:\...target-dir...\"</code><br/>
For WiX - use <a href="https://github.com/wixtoolset/wix3/releases/">wix-toolset</a>'s <code>dark.exe</code>:
<code>dark.exe myinstaller.exe -x "C:\...target-dir...\"</code>.
<br/>
WiX installers are always exe-files, with the same signature
as classic MSI installers <em>(successfully identified even back in the uniextract-v1.6 days)</em>.

<hr/>

I think <code>dark.exe</code> will <strong>only support
extracting the new WiX format</strong>, so you may included
it as a fallback for "self-extracted MSI" files which fail to extract using older-methods.

Hope it helps !

**Comment by Bioruebe** [comment]
Thanks for your suggestion, support has been added with 45414bf76221a32ded82e53b7abcafd510bec574.
