### ISSUE TITLE
Download or document LiveMaker.cui

### ISSUE THREAD

**Issue by livermek** [Bioruebe/UniExtract2#77]
While this isn't part of UniExtract exactly, since it's the plugin of a plugin, it's mentioned specifically in the description for crass/crage.exe with no further elaboration on where you might find it, since it isn't included with crass:

> "Extractor for several game engines. Livemaker extraction requires additional file 'cui\Livemaker.cui'"

There should be some kind of mention of where that additional file is supposed to come from. If it could be downloaded just like crass itself is, even better.

**Comment by cubedj** [comment]
try sendspace.com together with /file/0103l3

**Comment by cubedj** [comment]
but its from tool "Livemaker" try http://www.livemaker.net/download/stab/ or http://www.livemaker.net/download/beta/

**Comment by Darthagnon** [comment]
For the record, the file goes in <bin/crass-[version-number]/cui/>

**Comment by Juesto** [comment]
This cui is unavailable on latest crass/crage.

**Comment by gjdunga** [comment]
https://github.com/rinrin-/crass/blob/master/crage/Release/cui/LiveMaker.cui
Click on the Raw and it will download.. 

This still does not answer how to satisfy the install procedure for Crass.

**Comment by gjdunga** [comment]
Also, from the Crass Readme... 

> the newest version:
		http://galcrass.blog124.fc2.com/

	cui update:
		http://galcrass.blog124.fc2.com/blog-entry-1.html

	partial cui source code(ver 1.0.4):
		http://www.aishare.net/link.php?ref=tYsE9l9Nyu

	quiz and bug report:
		https://www.yukict.com/bbs/thread-13010-1-1.html

	pcicp's CG rip blog:
		http://haibarascgrip.baywords.com/

>
