### ISSUE TITLE
Swedish translation encoding

### ISSUE THREAD

**Issue by eson57** [Bioruebe/UniExtract2#8]
Hi,

Swedish language file don't work when encoded UTF8. Please, convert to Unicode UCS-2 Little Endian, or even Ansi will work.

Thanks for new release.  :+1:

**Comment by Bioruebe** [comment]
Whoops. Good that you noticed it so fast, so I could just modify the update packages before it gets downloaded too often.

**Comment by eson57** [comment]
Thanks!  :)
