### ISSUE TITLE
7-Zip vulnerable – update to version 18.01

### ISSUE THREAD

**Issue by purecut** [Bioruebe/UniExtract2#81]
Older versions of the packer available for various platforms have security vulnerabilities. An update should be carried out as soon as possible.

quote from   https://borncity.com/win/2018/01/30/7-zip-vulnerable-update-to-v18-0-1/

**Comment by rmenessec** [comment]
Latest release of 7-Zip is now 18.03. Please update.

**Comment by vgturtle127** [comment]
👍 

Yes, updating this should happen before a public release.

**Comment by wvxwxvw** [comment]
The new 7ZSplit.exe is now called SfxSplit.exe
Comstrokeys
-m <file for module>
-a <file for archive>
-c <file for config>
-b silent mode
https://www.upload.ee/files/8442501/SfxSplit.zip.html
The author's website does not open.

**Comment by Darthagnon** [comment]
Can the 7-zip modules in <bin/x86> be updated manually? Can 7zSplit.exe be replaced with a renamed SfxSplit.exe, that you linked, @wvxwxvw ?

**Comment by BravoOneCharlie** [comment]
I believe UniExtract uses an old version because newer versions of 7-zip removed the ability to extract NSIS Archives. "Removed 7zip 15.14, reverted to 15.05 as NSIS support was dropped from newer versions" https://github.com/Bioruebe/UniExtract2/releases/tag/v2.0.0-beta.3

**Comment by wvxwxvw** [comment]
The ability to extract NSIS scripts is not removed, but commented.
.\CPP\7zip\Archive\Nsis\NsisIn.h string 19
It is possible and ready binaries to find, for example
http://forum.ru-board.com/topic.cgi?forum=5&topic=49016&start=760#5

**Comment by rmenessec** [comment]
Whatever approach is taken, I'd prefer it err on the side of security.

**Comment by BravoOneCharlie** [comment]
I personally would prefer it to err on the side of functionality.
