### ISSUE TITLE
[Request] Extracting MSI but keeping the result folder install'able.

### ISSUE THREAD

**Issue by eladkarako** [Bioruebe/UniExtract2#85]
Extracting `.msi` archive (in v1.6) creates a functional "installation folder",
complete with a modified `.msi` file that points to the files inside the folder (instead of the content of a `.cab` file, for example).

old:
<img src="https://i.imgur.com/XWTpF3S.gif" />

new:
<img src="https://i.imgur.com/CSzX8n1.gif" />

<hr/>

the newer version is obviously much better with extracting msi files,
but I was quite fond of the old way, mostly since it allowed me to "flatten" installations to a folder,
which I then compressed with 7zip to get a much better compression-ratio.

any way I can bring it back some way?

**Comment by Bioruebe** [comment]
Did you find a solution to the issue?

I'm not against keeping it installable, I just didn't have time to look into the issue yet. UE 2 uses a different extractor, which does not create a modified installer file. I could simply re-enable the extractor selector from 1.6, but the new one works better (less failed extractions) and the user does not have to choose, which is quite an advantage imo.

If the feature is important for you, you can try to ask the developer of the extractor at [activescott/lessmsi](https://github.com/activescott/lessmsi).
Feel free to reopen the issue :)
