### ISSUE TITLE
Add documentation how to use this

### ISSUE THREAD

**Issue by DreamFlasher** [Bioruebe/UniExtract2#86]
Apparently these are some autoit scripts, but who knows. Can you please add the necessary steps to use this? (This project differs from standard ways like binary executables)

**Comment by vatterspun** [comment]
I can assist with this if needed.  Let me know.

**Comment by DreamFlasher** [comment]
I got it to run in the end, what is missing from an end-user perspective: In the Readme a section that references the current release -- so that people know that they don't checkout the repo, but need the release. And then I think what would be helpful is a section on how to compile the repo to build the binarys oneself.

**Comment by vatterspun** [comment]
> what would be helpful is a section on how to compile the repo to build the binarys oneself

That's something I definitely wish was very clearly spelled out in every open source distribution.  Too many programs get a lot of attention by being open source but leave out bits and pieces that prevent compiling, which doesn't encourage the involvement open source is supposed to kindle.  I haven't checked out whether this is an issue with UE2, more something I'd just like to see by default.  Like posting something to Github, you have to check "did you include compile instructions" and have that displayed on the source page somewhere that the dev is claiming those are present.

**Comment by Bioruebe** [comment]
@DreamFlasher Thanks for the feedback. I added a download link and some information about building from source to the readme.


@vatterspun Very true, open source and good documentation are two things that don't seem to go together very well... I even encoutered plain wrong documentation. *That* really makes you wonder what's the issue.

For UE, I didn't think instructions were necessary. (Everyone, who worked with Autoit before, should know how to build an executable ;) ) Now instructions are part of the readme, so everyone should be able to build it. If something is unclear, just ask me or open a pull request :)

**Comment by DreamFlasher** [comment]
Thank you @Bioruebe

**Comment by vatterspun** [comment]
> For UE, I didn't think instructions were necessary.

UE is pretty simple and that's always been a great asset to it's popularity over time.  I definitely wouldn't change that and, where ever possible, try to write it so docs just an accessory.

Still, there's always 3 types of docs: 

1. An intro (videos are good) that answer 'why should I care / what does this even do?'
2. Tips and tricks - how to use it better, optional settings, etc.  For example, what functionality the included FFMPEG offers and how that's useful, etc. 
3. Advanced Operations - getting your hands dirty with the internals.  Swapping out extraction bits, maybe some statement about why one tool was chosen over another.  Maybe some notes about the program history and your approach.

I might not have much to assist on 3, but I have some expertise on 1 and 2.
