### ISSUE TITLE
UniArchive (reverse UniExtract) possible?

### ISSUE THREAD

**Issue by Darthagnon** [Bioruebe/UniExtract2#87]
Univeral Extractor extracts anything; would incorporating some sort of Universal Archiving (i.e. re-archive anything) be possible, or is it beyond the scope of this project? Probably a stupid question; can't hurt to ask...

**Comment by mirh** [comment]
Extracting everything (==> to plain file) is a pretty plain one way process. 
Compressing is.. Well, there are tons of variables at play.

**Comment by Bioruebe** [comment]
Possible? Yes. 
Will I do it? Probably not.
As you already conceived, that's a bit out of scope.

Also, I cannot think of a reason to compress with all kind of different methods. Zip, rar and 7z are standard by now, provide great compression and can be opened almost every device. Programs like 7zip are already able to compress using different algorithms. So why create archives, which no one can open and have bad compression?
Some formats can create slightly smaller archives, but disk space isn't that limited or expensive anymore.
UniArchiving game archives would be quite nice for modders or fan translations, but this would be way too much work to support thousands of formats.

**Comment by Darthagnon** [comment]
Thanks for the reply! Perhaps another silly question, but is it possible for users to add their own extract/compress plugins to UniExtract in its present state? Just a thought, so that maybe modders, etc. could implement the functions they need as and when, by themselves...

**Comment by Bioruebe** [comment]
Yes, but not in a very convenient way and the plugin system is still somewhat limited.
Like: updating might disable custom plugins, only one extractor per file type is possible and UniExtract's built-in extractors cannot be replaced with your own tools. Oh, and of course, no documentation yet (I plan on adding some infos).

**Comment by Darthagnon** [comment]
"UniCompressor" exists!!!

I found it while researching; it's called [UltraArc](https://fileforums.com/showthread.php?t=96619). More info [here](https://custom-installer-ultimate-v2.fandom.com/wiki/UltraArc)

Might be worth linking in the relevant section in the readme?
