### ISSUE TITLE
RPGMaker Decrypter plugin link is down

### ISSUE THREAD

**Issue by Darthagnon** [Bioruebe/UniExtract2#88]
The RPGMaker Decrypter plugin module link in the plugins list is dead. I can't find the specific version of the decrypter required by UniExtract2 online, though I have seen a few similar ones (e.g. I've unsuccessfully tried: https://github.com/uuksu/RPGMakerDecrypter, https://wiki.f95zone.com/RPG_Maker_Decrypter) (I've also seen but not tried: https://wiki.rpgmaker.es/ayuda/utilidades/rpg-maker-xp-vx-vx-ace-decrypter, https://f95zone.com/threads/rpg-maker-unpacker.50/) **(edit: just realised that the f95zone sites are NSFW - be warned)**

Any advice?

**Comment by BravoOneCharlie** [comment]
I looked around a bit and I found it here: https://drive.google.com/file/d/1Vm-QnOJaWUnRWMmiPiI7UbP8xpnR3xaQ/view?usp=sharing

**Comment by Darthagnon** [comment]
Thank you very much, @BravoOneCharlie !

**Comment by Darthagnon** [comment]
@Bioruebe , please could you update UniExtract2 with the updated link to this plugin?

**Comment by BravoOneCharlie** [comment]
I'm not sure if that link will last, Google Drive links tend to disappear.

**Comment by BravoOneCharlie** [comment]
Looks like it already got deleted. This is the only other place I found it at. https://yun.baidu.com/share/link?uk=3191213670&shareid=636741

**Comment by Bioruebe** [comment]
Thanks for your report.

Looks like there are some better alternatives now, so I decided to replace the extractor. The next build will come with built-in rgss support, no plugin needed.

**Comment by Cool-Pan** [comment]
I found a Java version and didn't know if it was what you needed.

[Java-RPG-Maker-MV-Decrypter](https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter)
