### ISSUE TITLE
Unreal Engine Resource Viewer plugin link is down

### ISSUE THREAD

**Issue by Darthagnon** [Bioruebe/UniExtract2#89]
Title says it all.

**Comment by BravoOneCharlie** [comment]
The link must have been changed or something, it's available here: http://www.gildor.org/en/projects/umodel#files

**Comment by Darthagnon** [comment]
Thank you very much :D

**Comment by Bioruebe** [comment]
Fixed in RC 1

**Comment by stdedos** [comment]
On RC2 and still broken 😕
