### ISSUE TITLE
AutoIt Error regarding illegal text.

### ISSUE THREAD

**Issue by vBm** [Bioruebe/UniExtract2#9]
I've tried to unpack Inno installer and got this error.
Do note that beta 1 worked just fine.

![2016-02-09_01-24-00](https://cloud.githubusercontent.com/assets/80596/12903930/f9f5fd72-cecb-11e5-8d6a-5bff61cdbc68.png)

**Comment by Bioruebe** [comment]
There was a little problem with the beta 2 release, please manually search for updates to get a fixed version.

**Comment by mikhoul** [comment]
> There was a little problem with the beta 2 release, please manually search for updates to get a fixed version.

I've updated directly to beta 2  from beta 1 with the update function and everything seemed fine till I try to open some files...

![http://i.imgur.com/xLsbi6H.png](http://i.imgur.com/xLsbi6H.png)

I even tried to reinstall beta 1 after but nothing improved I had to delete the whole installation folder and reinstall the beta one manually (Drag and drop archive file like a portable app) .

Let me know what happen with beta 2 installer.

Suggestion to put an uninstaller for the app. :blush:

Regards ! :zap:

**Comment by Bioruebe** [comment]
Hmm, strange. You should have been able to update from beta 2 to beta 2b with the update function. I released a hotfix for this error right after the first reports reached me.

I hope you could get it to work by now.
A real installer and uninstaller will be added after the beta test.

**Comment by vBm** [comment]
Sorry for not getting back right after. Even after i've tried to run updater and download/update is completed, app still says there's a  beta2b update available. Seems like updater doesn't replace/patch files at all thus leaving us with the same issue all over again.

**Comment by Bioruebe** [comment]
The latest commit introduces a new update mechanism which should solve most of the issues. If you still have problems, please try to run UniExtract as administrator or move the whole UE folder to a directory you have full write permissions (ie. not \program files).
