### ISSUE TITLE
Subscript used on non-accessible variable

### ISSUE THREAD

**Issue by artlantis** [Bioruebe/UniExtract2#96]
When I click the "Preferences" link from the menu the application throwing the following error message

> Line 26171 (File "..\UniExtract.exe")
> Error : Subscript used on non-accessible variable.

OS : Windows 10 x64, Turkish
UniExtract : 2.0 Beta 4 and I started the program with admin privileges

**Comment by FredThompsonII** [comment]
I have the same error on a different line and different build:

Line 28291
Universal Extractor 2 2.0.0 RC1

**Comment by HapaxOromenon** [comment]
It seems to work for me on the latest build - try downloading the newest UniExtract.au3 and compiling it to give a new UniExtract.exe.

**Comment by Bioruebe** [comment]
Does it still happen in RC2?
