### ISSUE TITLE
ffmpeg update error

### ISSUE THREAD

**Issue by FredThompsonII** [Bioruebe/UniExtract2#97]
Universal Extractor 2 2.0.0 RC1

Current build of ffmpeg is 4.0x
UniExtractUpdater says it is downloading 3.4.2x then fails, reporting the file cannot be downloaded.

**Comment by FredThompsonII** [comment]
When I first see this message, if I do NOT download the ffmpeg update, the updates does update other files.
The next time, I chose to try the download, it failed, and reported line 6969 in UniExtractUpdater_NoAdmin
Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded.

Hope this information helps pinpoint the problems.

**Comment by Bioruebe** [comment]
Thanks for the bug report. The error was caused by some leftover code from the old updater, which I forgot to remove.

Please try updating UniExtract first, then downloading ffmpeg should work.
